<?php
/**
 * @file
 * @author Chun-Yu Lee (Mat) <matlinuxer2@gmail.com>
 * @version 20140330_700b33f
*/define("version.libMat","1.0.5");$ja=(basename(__FILE__)=="Mat.php")?dirname(__FILE__)."/..":dirname(__FILE__);define("MROOT",$ja);class
Database{private$sa="localhost";private$ua="3306";private$va=false;private$xa=NULL;private$ta=NULL;private$pa=NULL;protected
function
__construct(){}public
function
setup($tg="localhost",$vm="3306",$Er,$Ll){$this->_host=$tg;$this->_port=strval($vm);$this->_user=$Er;$this->_pass=$Ll;}function
isConnected(){if($this->_resource===false)return
false;else
return
true;}function
set_encoding($Ke,$Le){$G=mysql_query("SET NAMES $Ke",$this->_resource);$G=mysql_query("SET collation_connection='".$Le."' ",$this->_resource);}function
get_database(){return$this->_database;}function
set_database($Ud){$J=0;$this->_database=$Ud;$Jh=mysql_selectdb($this->_database,$this->_resource);if(!$Jh)$J=-1;return$J;}function
connect(){$J=0;$K=NULL;if(!$this->_resource){if($this->_host!=NULL&&$this->_port!="0"){$this->_resource=mysql_connect($this->_host.":".$this->_port,$this->_user,$this->_pass);if($this->_resource!==false)$J=0;else$J=-1;}else$J=-2;}return$K;}function
disconnect(){if($this->_resource!==false){mysql_close($this->_resource);$this->_resource=false;}}function
list_databases(){$F="SELECT TABLE_SCHEMA"." FROM information_schema.TABLES "." WHERE TABLE_SCHEMA != 'information_schema' AND table_schema != 'mysql' "." GROUP BY TABLE_SCHEMA ";$H=$this->query($F);$Vd=array();foreach($H
as$L)array_push($Vd,$L["TABLE_SCHEMA"]);return$Vd;}function
list_tables($n){$F="SELECT TABLE_SCHEMA, TABLE_NAME"." FROM information_schema.TABLES "." WHERE TABLE_SCHEMA = '".$n."' "."";$H=$this->query($F);$P=array();foreach($H
as$L)array_push($P,$L["TABLE_NAME"]);return$P;}function
list_columns($n,$O){$h=array();$F="SELECT * "." FROM information_schema.COLUMNS "." WHERE TABLE_SCHEMA = '".$n."' "." AND TABLE_NAME = '".$O."' "."";$H=$this->query($F);foreach($H
as$L)array_push($h,$L);return$h;}function
describe_table($n,$O){$h=array();$F="DESCRIBE $n.$O ";$H=$this->query($F);foreach($H
as$L)array_push($h,$L);return$h;}function
list_table_primary_key($n,$O){$h=array();$F="SELECT * "." FROM information_schema.COLUMNS "." WHERE TABLE_SCHEMA = '".$n."' "." AND TABLE_NAME = '".$O."' "." AND COLUMN_KEY = 'PRI' "."";$H=$this->query($F);foreach($H
as$L)array_push($h,$L['COLUMN_NAME']);return$h;}function
check_schema($o,$Q,$fd){$h=$this->list_columns($o,$Q);$Ih=false;foreach($h
as$L){if($fd===$L['COLUMN_NAME'])$Ih=true;}if($Ih)return
true;else
return
false;}function
add_schema($o,$Q,$fd,$T,$Nh,$je,$nd){$H=false;$Nk="";if($Nh)$Nk="NULL";else$Nk="NOT NULL";if(gettype($je)==="NULL")$je="NULL";$F="ALTER TABLE `$o`.`$Q` "." ADD `$fd` "." $T "." $Nk "." DEFAULT $je "." COMMENT '$nd'";echo$F."\n";@$I=$this->query_nodata($F);if($I===0)$H=true;else$H=false;return$H;}function
query($F){$J=0;$K=NULL;if($this->_resource!==false){$G=mysql_query($F,$this->_resource);if($G!==false){$H=array();while($L=mysql_fetch_assoc($G))array_push($H,$L);$K=$H;}else$J=-1;}else$K=NULL;return$K;}function
query_nodata($F){$J=0;if($this->_resource!==false){$G=mysql_query($F,$this->_resource);if($G!==false)$J=0;else$J=-2;}else$J=-1;return$J;}static
private$a=null;static
public
function
getInstance(){if(!self::$a)self::$a=new
self;return
self::$a;}}class
TblObj{public$c=NULL;public$wa="";private$qa=NULL;private$ra=NULL;private
function
_check_db(){if($this->_db==NULL){$this->_db=Database::getInstance();$this->_dbname=$this->_db->get_database();}if($this->_db->isConnected())return
true;else
return
false;}public
function
exists(){$H=false;if(!$this->_check_db())return$H;$oq=get_class($this);$P=$this->_db->list_tables($this->_dbname);if(in_array($oq,$P))$H=true;return$H;}public
function
columns(){$H=array();if(!$this->_check_db())return$H;$oq=get_class($this);$h=$this->_db->describe_table($this->_dbname,$oq);foreach($h
as$L)array_push($H,$L['Field']);return$H;}public
function
primary_key(){return$this->_primary_key;}public
function
primary_val(){$fd=$this->_primary_key;return$this->$fd;}public
function
create(){$H=false;if(!$this->_check_db())return$H;$h=array();foreach($this
as$x=>$Z){if(substr($x,0,1)=="_")continue;$wr=explode(",",$this->_unique);switch(gettype($Z)){case"integer":$M=" int(10) ";break;case"string":default:$M=" varchar(255) ";}if(in_array($x,$this->_not_nulls))$M.=" NOT NULL ";if($x==$this->primary_key()){$M.=" PRIMARY KEY ";if(gettype($Z)=="integer")$M.=" AUTO_INCREMENT ";}if(in_array($x,$wr))$M.=" UNIQUE";array_push($h,"`$x` $M");}$F="CREATE TABLE IF NOT EXISTS ".get_class($this)." ( \n";$F.=implode(",\n",$h)."\n";$F.=")";@$I=$this->_db->query_nodata($F);if($I===0)$H=true;else$H=false;return$H;}public
function
insert(){$H=false;if(!$this->_check_db())return$H;$y=array();$as=array();foreach($this
as$x=>$Z){if(substr($x,0,1)=="_")continue;if($x==$this->primary_key())continue;array_push($y,"`$x`");switch(gettype($Z)){case"integer":array_push($as,"$Z");break;case"string":default:array_push($as,"'$Z'");break;}}$F="INSERT INTO `".get_class($this)."` ( ";$F.=implode(",",$y);$F.=") VALUES ( ";$F.=implode(",",$as);$F.=")";@$I=$this->_db->query_nodata($F);if($I===0)$H=true;else$H=false;return$H;}public
function
select($zd=NULL){$H=array();if(!$this->_check_db())return$H;$Ad="";$T=gettype($zd);if($T=="array"){$p=array();foreach($zd
as$x=>$X){if(substr($x,0,1)=="_")continue;switch(gettype($X)){case"NULL":array_push($p,"`$x`=NULL");break;case"integer":array_push($p,"`$x`=$X");break;case"string":default:array_push($p,"`$x`='$X'");break;}}if(count($p)>0)$Ad=" AND ( ".implode(" AND ",$p)." ) ";}else
if($T=="string")$Ad=$zd;else
if($T=="NULL")$Ad="";else$Ad=" AND 1=0 ";$F="SELECT * FROM ".get_class($this)." WHERE 1=1 ".$Ad;@$I=$this->_db->query($F);if($I!=NULL){foreach($I
as$G){$fp=get_class($this);$v=new$fp();$v->load_array($G);array_push($H,$v);}}return$H;}public
function
selectOne($_d=NULL){$H=NULL;if(!$this->_check_db())return$H;if(!is_array($_d)){$w=$this->primary_key();$W=$this->primary_val();$_d=array($w=>$W);}$p=array();foreach($_d
as$x=>$X){if(substr($x,0,1)=="_")continue;switch(gettype($X)){case"NULL":array_push($p,"`$x`=NULL");break;case"integer":array_push($p,"`$x`=$X");break;case"string":default:array_push($p,"`$x`='$X'");break;}}$F="SELECT * FROM `".get_class($this)."` WHERE 1=1 ";if(count($p)>0)$F.=" AND ( ".implode(" AND ",$p)." ) ";$F.=" LIMIT 1";@$I=$this->_db->query($F);if($I!=NULL){foreach($I
as$G){$fp=get_class($this);$v=new$fp();$v->load_array($G);$H=$v;}}return$H;}public
function
update($h=NULL){$H=false;if(!$this->_check_db())return$H;$p=array();foreach($this
as$x=>$Z){if(substr($x,0,1)=="_")continue;if(is_array($h)){if(!in_array($x,$h))continue;}else
if(is_string($h)){if($x!==$h)continue;}switch(gettype($Z)){case"integer":array_push($p,"$x=$Z");break;case"string":default:array_push($p,"$x=\"$Z\"");break;}}$Vm=$this->primary_key();$Xm=$this->primary_val();$F="UPDATE ".get_class($this)." SET ";if(count($p)>0)$F.=implode(",",$p);$F.=" WHERE `$Vm`=".$Xm."";@$I=$this->_db->query_nodata($F);if($I===0)$H=true;else$H=false;return$H;}public
function
delete(){$H=false;if(!$this->_check_db())return$H;$Vm=$this->primary_key();$Xm=$this->primary_val();$F="DELETE FROM ".get_class($this)." ";$F.=" WHERE `$Vm`=".$Xm."";@$I=$this->_db->query_nodata($F);if($I===0)$H=true;else$H=false;return$H;}public
function
dump_array(){$H=array();foreach($this
as$x=>$Z){if(substr($x,0,1)=="_")continue;$H[$x]=$Z;}return$H;}public
function
load_array($yh){foreach($this
as$x=>$Z){if(substr($x,0,1)=="_")continue;if(array_key_exists($x,$yh))$this->$x=$yh[$x];}}}function
sketch_tblobj($Zd,$oq){$H="";$o=Database::getInstance();$P=$o->list_tables($Zd);if(!in_array($oq,$P))return$H;$kd="";$Wm="";$vh="";$bn=array();$Hk=array();$wh=array();$h=$o->list_columns($Zd,$oq);foreach($h
as$L){$gd=$L['COLUMN_NAME'];if($L['IS_NULLABLE']==='NO')array_push($Hk,$gd);$M=$L['DATA_TYPE'];if($L['COLUMN_KEY']==='PRI')array_push($bn,$gd);}if(count($bn)===1){$Vm=$bn[0];$Wm=sprintf("	public \$_primary_key = \"%s\";",$Vm);}if(count($Hk)>0){$nr="array(\n\t\t\"".implode("\",\n\t\t\"",$Hk)."\"\n\t\t)";$Gk=sprintf("	public \$_not_nulls = %s;",$nr);}foreach($h
as$L){$gd=$L['COLUMN_NAME'];$M=$L['DATA_TYPE'];$x=$gd;$X=NULL;switch($M){case"varchar":case"char":case"longtext":case"mediumtext":case"text":case"tinytext":case"blob":case"longblob":$X="\"\"";break;case"date":case"datetime":case"time":case"timestamp":$X="NULL";array_push($wh,sprintf("\$this->%s = new DateTime();",$x));break;case"int":case"bigint":case"mediumint":case"smallint":case"tinyint":$X="0";break;case"decimal":case"double":case"float":$X="0.0";break;default:case"enum":case"set":$X=NULL;break;}if($X!=NULL)$kd.=sprintf("	public \$%s = %s ; \n",$x,$X);}foreach($wh
as$L)$vh.="\t\t$L\n";$hm=<<<EOF
class %s extends TblObj {
%s
%s
%s
	public function __construct(){
%s
	}
}

EOF;
$im=sprintf($hm,$oq,$kd,$Wm,$Gk,$vh);echo$im;}class
Feedback{public$V="";public$zr="";public$aq="";public$l="";public$us="";public$vs="";public$qo=-1;public$vo="";public
function
pack(){$J=0;$K="";$m=array();foreach($this
as$x=>$Z)$m[$x]=$Z;$K=base64_encode(serialize($m));return$K;}public
function
unpack($xh){$J=0;$K="";$Pk=unserialize(base64_decode($xh));foreach($Pk
as$x=>$Z)$this->$x=$Z;return$J;}public
function
show(){echo"<pre>",$this->uuid,"\n",$this->url,"\n",$this->subject,"\n",$this->content,"\n",$this->when,"\n",$this->who,"</pre>";}}class
FeedbackMgr{private$if=null;public
function
get($t){$K=NULL;$J=0;foreach($this->feedbacks
as$v){if($t==$v->uuid)$K=$v;}return$K;}public
function
lists(){return$this->feedbacks;}public
function
add($A){$J=0;$K="";if($A->uuid=="")$J=-1;else
if($A->url=="")$J=-2;else
if($A->content=="")$J=-3;else{$Hh=false;foreach($this->feedbacks
as$v){if($A->url==$v->url&&$A->content==$v->content)$Hh=true;}if($Hh===true)$J=-4;else
array_push($this->feedbacks,$A);}return$J;}public
function
del($Xk){$J=0;$K="";$dd=0;for($s=0;$s<count($this->feedbacks);$s++){$v=$this->feedbacks[$s];if($Xk->uuid==$v->uuid){unset($this->feedbacks[$s]);$dd++;}}if($dd==0)$J=-1;else
if($dd>1)$J=1;return$J;}public
function
edit($A){$J=0;$K="";foreach($this->feedbacks
as$v){if($A->uuid==$v->uuid){foreach($A
as$x=>$Z)$this->$x=$Z;}}return$J;}public
function
save($Nl){$J=0;$K="";$m="";for($s=0;$s<count($this->feedbacks);$s++){$v=$this->feedbacks[$s];if($v!=NULL)$m=$m.($v->pack())."\n";}$I=file_put_contents($Nl,$m,LOCK_EX);if($I===FALSE)$J=-1;else;return$J;}public
function
load($Nl){$J=0;$K="";$m=file_get_contents($Nl);$Ji=explode("\n",$m);$Sh=array();for($s=0;$s<count($Ji);$s++){if($Ji[$s]!=""){$v=new
Feedback();$v->unpack($Ji[$s]);array_push($Sh,$v);}}$this->feedbacks=$Sh;return$J;}}class
Logger0{private$Ef=null;private$Cm=null;private$ob=null;protected
function
__construct(){}public
function
setup($Nl){ini_set('error_log',$Nl);}public
function
log($Gj,$Ik=false){error_log($Gj);}public
function
debug($Gj,$Ik=false){$Ok=func_num_args();$zb=func_get_args();}static
public
function
errorHandler($Se,$Te,$Qe,$Re,$Pe){$gk='Into '.__FUNCTION__.'() at line '.__LINE__."\n\n---ERRNO---\n".print_r($Se,true)."\n\n---ERRSTR---\n".print_r($Te,true)."\n\n---ERRFILE---\n".print_r($Qe,true)."\n\n---ERRLINE---\n".print_r($Re,true)."\n\n---ERRCONTEXT---\n".print_r($Pe,true)."\n\nBacktrace of errorHandler()\n".print_r(debug_backtrace(),true);$Wi=Logger::getInstance();$Wi->debug($gk,false);}static
public
function
exceptionHandler($Ue){$gk="Uncaught exception: ".$Ue->getMessage()."\n";$Wi=Logger::getInstance();$Wi->debug($gk,false);}static
private$a=null;static
public
function
getInstance(){if(!self::$a)self::$a=new
self;return
self::$a;}}class
RequestClass{private$Ef=null;private$Cm=null;private$ob=null;public
function
read(){$this->get_data=$_GET;$this->post_data=$_POST;$this->all_data=array_merge($this->get_data,$this->post_data);}public
function
set($w,$W){$this->all_data[$w]=$W;}public
function
get($w){return$this->all_data[$w];}public
function
gen(){$El=array();foreach($this->all_data
as$x=>$Z){$nr="$x=".urlencode($Z);array_push($El,$nr);}$Fl=implode('&',$El);return$Fl;}}class
Conf{private$oa=array();protected
function
__construct(){require_once(dirname(__FILE__)."/../../Config/conf.global.php");require_once(dirname(__FILE__)."/../../Classes/function.php");$fa=new
FUNCTIONS();if(isset($INFO)){foreach($INFO
as$x=>$X){$w="DEFAULT.".$x;$this->_data[$w]=$X;}$this->_data["DEFAULT.DBname"]=$fa->authcode($INFO['DBname'],"DECODE",$INFO['site_userc']);$this->_data["DEFAULT.DBuserName"]=$fa->authcode($INFO['DBuserName'],"DECODE",$INFO['site_userc']);$this->_data["DEFAULT.DBpassword"]=$fa->authcode($INFO['DBpassword'],"DECODE",$INFO['site_userc']);}}public
function
lists($ri){$y=array_keys($this->_data);return$y;}public
function
get($x){$d=explode(".",$x);if(count($d)==1)$x="DEFAULT.".$x;return$this->_data[$x];}public
function
set($x,$X){$d=explode(".",$x);if(count($d)==1)$x="DEFAULT.".$x;$this->_data[$x]=$X;}static
private$a=null;static
public
function
getInstance(){if(!self::$a)self::$a=new
self;return
self::$a;}}function
isCLI(){$Mn=isset($_SERVER["REMOTE_ADDR"])?$_SERVER["REMOTE_ADDR"]:"";$Xj=php_sapi_name();if($Xj=="cli")return
TRUE;else
if($Xj=="cgi"&&$Mn=="")return
TRUE;else
return
FALSE;}function
big52utf8($cc){$ec=strlen($cc);$Yr="";for($s=0;$s<$ec;$s++){$Vo=ord(substr($cc,$s,1));if($Vo<129)$Yr.=substr($cc,$s,1);elseif($Vo>128&&$Vo<255){$rk=iconv("BIG5","UTF-8",substr($cc,$s,2));$Yr.=($rk=="")?"?":$rk;$s++;}}return$Yr;}function
utf82big5($Yr){$cc=iconv("UTF-8","BIG5//IGNORE",$Yr);return$cc;}function
utf8_to_big5($zq){$H="";$N="//IGNORE";$Xr=$zq;$bc=iconv("UTF-8","BIG-5".$N,$Xr);$H=$bc;return$H;}function
big5_to_utf8($zq){$H="";$N="//IGNORE";$bc=$zq;$Xr=iconv("BIG-5","UTF-8".$N,$bc);$H=$Xr;return$H;}function
text_tw2cn($zq){$H="";$N="//IGNORE";$Xr=$zq;$bc=iconv("UTF-8","BIG-5".$N,$Xr);$bc=iconv("UTF-8","BIG-5".$N,$Xr);$yf=iconv("BIG-5","GB2312".$N,$bc);$Wr=iconv("GB2312","UTF-8".$N,$yf);$H=$Wr;return$H;}function
select_files($Rm,$De){$qf=scandir($De);$H=array();$s=0;foreach($qf
as$w=>$W){$wm=strpos($W,$Rm);if($wm!==FALSE&&$wm===0){$H[$s]=$W;$s++;}}return$H;}function
rstr($_){$_=str_replace(",","，",$_);$_=str_replace("\"","“",$_);$_=str_replace("\r"," ",$_);$_=str_replace("\n"," ",$_);return$_;}function
isPOST(){if(isCLI())return
false;if($_SERVER['REQUEST_METHOD']&&$_SERVER['REQUEST_METHOD']!='POST')return
true;else
return
false;}function
uuidgen($tp=false,$Ve=false){$Tp=array();$cd="uuidgen 2>&1";$Sp=-100;$V=null;$qg=false;if($Ve)exec($cd,$Tp,$Sp);if($Sp==0&&count($Tp)){$V=$Tp[0];if(strlen($V)==36){$qg=true;$V=strtoupper($V);}}if(!$qg){$z=strtoupper(md5(uniqid(microtime(true),true)));$V=sprintf("%04s%04s-%04s-%04s-%04s-%04s%04s%04s",$z[0].$z[1].$z[2].$z[3],$z[4].$z[5].$z[6].$z[7],$z[8].$z[9].$z[10].$z[11],$z[12].$z[13].$z[14].$z[15],$z[16].$z[17].$z[18].$z[19],$z[20].$z[21].$z[22].$z[23],$z[24].$z[25].$z[26].$z[27],$z[28].$z[29].$z[30].$z[31]);}if($tp)$V=sha1($V);$V=strtolower($V);return$V;}function
isFromMobile(){$Vj=0;if(preg_match('/(up.browser|up.link|mmp|symbian|smartphone|midp|wap|phone)/i',strtolower($_SERVER['HTTP_USER_AGENT'])))$Vj++;if((strpos(strtolower($_SERVER['HTTP_ACCEPT']),'application/vnd.wap.xhtml+xml')>0)or((isset($_SERVER['HTTP_X_WAP_PROFILE'])or
isset($_SERVER['HTTP_PROFILE']))))$Vj++;$Wj=strtolower(substr($_SERVER['HTTP_USER_AGENT'],0,4));$Uj=array('w3c ','acs-','alav','alca','amoi','audi','avan','benq','bird','blac','blaz','brew','cell','cldc','cmd-','dang','doco','eric','hipt','inno','ipaq','java','jigs','kddi','keji','leno','lg-c','lg-d','lg-g','lge-','maui','maxo','midp','mits','mmef','mobi','mot-','moto','mwbp','nec-','newt','noki','oper','palm','pana','pant','phil','play','port','prox','qwap','sage','sams','sany','sch-','sec-','send','seri','sgh-','shar','sie-','siem','smal','smar','sony','sph-','symb','t-mo','teli','tim-','tosh','tsm-','upg1','upsi','vk-v','voda','wap-','wapa','wapi','wapp','wapr','webc','winw','winw','xda','xda-','Googlebot-Mobile');if(in_array($Wj,$Uj))$Vj++;if(strpos(strtolower($_SERVER['ALL_HTTP']),'OperaMini')>0)$Vj++;if(strpos(strtolower($_SERVER['HTTP_USER_AGENT']),'windows')>0)$Vj=0;if($Vj>0)return
true;else
return
false;}class
ntssi_admin_info
extends
TblObj{public$uh=0;public$th="";public$Jq="";public$c="info_id";public$b=array("info_id","info_content","title");public
function
__construct(){}}class
ntssi_adminip
extends
TblObj{public$t=0;public$Gh="";public$c="id";public$b=array("id","ip");public
function
__construct(){}}class
ntssi_administrator
extends
TblObj{public$yo=0;public$xo="";public$Kn="";public$T=0;public$c="sa_id";public$b=array("sa_id","sa","pw","type");public
function
__construct(){}}class
ntssi_adminlog
extends
TblObj{public$t=0;public$Oa="";public$l="";public$Gh="";public$fj="";public$c="id";public$b=array("id","admin","content","ip","logtime");public
function
__construct(){}}class
ntssi_advertising
extends
TblObj{public$Ta=0;public$ab="";public$cb=0;public$Sa=0;public$Kq="";public$Wa="";public$Ya="";public$Va="";public$Xa="";public$rm=0;public$Za="";public$Ua="";public$bb=0;public$Ra=0;public$Qa="";public$ad=0;public$ud="";public$Mp="";public$Ne="";public$xl=0;public$Fg=0;public$c="adv_id";public$b=array("adv_id","adv_title","adv_width","adv_height","title_color","adv_left_url","adv_right_url","adv_left_img","adv_right_img","point_num","adv_tag","adv_idate","adv_type","adv_display","adv_content","click_count","company","start_time","end_time","orderby","ifallclass");public
function
__construct(){}}class
ntssi_area
extends
TblObj{public$wb=0;public$xb="";public$yb=0;public$S=0;public$Is="";public$Bj="";public$c="area_id";public$b=array("area_id","areaname","areatype","top_id","zip","membercode");public
function
__construct(){}}class
ntssi_areatrans
extends
TblObj{public$Fb=0;public$eg=0;public$wb=0;public$c="at_id";public$b=array("at_id","group_id","area_id");public
function
__construct(){}}class
ntssi_article_tag
extends
TblObj{public$Gb=0;public$sk=0;public$qq=0;public$c="atid";public$b=array("atid","news_id","tagid");public
function
__construct(){}}class
ntssi_attribute
extends
TblObj{public$Lb=0;public$Kb="";public$c="attrid";public$b=array("attrid");public
function
__construct(){}}class
ntssi_attributeclass
extends
TblObj{public$Ea=0;public$Lb=0;public$Vc=0;public$Xe="";public$c="acid";public$b=array("acid","attrid","cid");public
function
__construct(){}}class
ntssi_attributegoods
extends
TblObj{public$hb=0;public$r=0;public$ds=0;public$c="agid";public$b=array("agid","gid","valueid");public
function
__construct(){}}class
ntssi_attributeno
extends
TblObj{public$qb=0;public$Ep="";public$jd="";public$r=0;public$Zf="";public$c="anid";public$b=array("anid","size","color","gid","goodsno");public
function
__construct(){}}class
ntssi_attributevalue
extends
TblObj{public$ds=0;public$Lb=0;public$Z="";public$Jd=0;public$c="valueid";public$b=array("valueid","value","count");public
function
__construct(){}}class
ntssi_bclass
extends
TblObj{public$ac=0;public$S=0;public$Gc="";public$Fc="";public$Dc="";public$Hc=0;public$Ec=0;public$Ib="";public$mm="";public$nm="";public$vf=0;public$Hj="";public$Ij="";public$Og=0;public$Il=0;public$Wb="";public$Xb="";public$ok=0;public$Ki="";public$Lo=0;public$On=0;public$Id=0;public$qj=0;public$cq=0;public$dq=0;public$c="bid";public$b=array("bid","top_id","catname","catord","catiffb","gain","ifhome","parent_id","banner","banner2","nclass","link","saleoff","rebate","costrebate","manyunfei","subject_id","subject_id2");public
function
__construct(){}}class
ntssi_bonus
extends
TblObj{public$t=0;public$On=0;public$c="id";public$b=array("id","rebate");public
function
__construct(){}}class
ntssi_bonus_record
extends
TblObj{public$bo=0;public$yl="";public$Pr=0;public$qm=0;public$Pn="";public$c="recordid";public$b=array("recordid","ordercode","userid","point","rebatetime");public
function
__construct(){}}class
ntssi_bonusalert
extends
TblObj{public$nb=0;public$mb="";public$lb=0;public$nj="";public$c="alertid";public$b=array("alertid","alertdate","alertcount","maillist");public
function
__construct(){}}class
ntssi_bonusbuydetail
extends
TblObj{public$t=0;public$U=0;public$l="";public$md=0;public$Dr=0;public$Vr="";public$zl=0;public$c="id";public$b=array("id","user_id","content","combipoint_id","usepoint","usetime","orderid");public
function
__construct(){}}class
ntssi_bonuscoll_goods
extends
TblObj{public$za=0;public$kc=0;public$Eb=0;public$id=0;public$U=0;public$Rr="";public$Ph="";public$Kp="";public$Yf="";public$u="";public$Cp="";public$Uf=0;public$c="abc_id";public$b=array("abc_id","bonusnum","askfor","collection_id","user_id","username","isay","ssay","goodsname","idate","sidate","goods_id");public
function
__construct(){}}class
ntssi_bonuscollection_goods
extends
TblObj{public$id=0;public$r=0;public$U=0;public$Wc="";public$c="collection_id";public$b=array("collection_id","gid","user_id","cidate");public
function
__construct(){}}class
ntssi_bonuspoint
extends
TblObj{public$t=0;public$qm=0;public$U=0;public$Ma="";public$Oe="";public$Ur=0;public$T=0;public$l="";public$Po=0;public$zl=0;public$c="id";public$b=array("id","point","user_id","addtime","endtime","usestate","type","content","saleorlevel","orderid");public
function
__construct(){}}class
ntssi_bonustype
extends
TblObj{public$sr=0;public$tr="";public$c="typeid";public$b=array("typeid","typename");public
function
__construct(){}}class
ntssi_brand
extends
TblObj{public$pc=0;public$rc="";public$qc="";public$ej="";public$is=0;public$Yc=0;public$sc="";public$Hj="";public$Ij="";public$c="brand_id";public$b=array("brand_id","brandname","viewcount","classid");public
function
__construct(){}}class
ntssi_buypoint
extends
TblObj{public$t=0;public$qm=0;public$T=0;public$U=0;public$Ma="";public$Ur=0;public$l="";public$zl=0;public$yo=0;public$zo=0;public$zc=0;public$ch=0;public$c="id";public$b=array("id","point","type","user_id","addtime","usestate","content","orderid","sa_id","sa_type","buypointtype","ifrefund");public
function
__construct(){}}class
ntssi_buypointrefund
extends
TblObj{public$nc=0;public$Rb="";public$Sb="";public$_a="";public$Fa="";public$ur=0;public$Np=0;public$do="";public$qm=0;public$io="";public$eo=0;public$U=0;public$Tr=0;public$C=0;public$ol=0;public$yc=0;public$c="br_id";public$b=array("br_id","bank","bankcode","account","acountname","u_id","state","refundtime","point","remark","refundtype","user_id","usertype","order_id","order_detail_id","buypoint_id");public
function
__construct(){}}class
ntssi_buypointtype
extends
TblObj{public$t=0;public$tr="";public$c="id";public$b=array("id","typename");public
function
__construct(){}}class
ntssi_collection_goods
extends
TblObj{public$id=0;public$r=0;public$U=0;public$Wc="";public$c="collection_id";public$b=array("collection_id","gid","user_id","cidate");public
function
__construct(){}}class
ntssi_company
extends
TblObj{public$t=0;public$xd="";public$l="";public$Ml="";public$Bi=0;public$E="";public$c="id";public$b=array("id","companyname","content","password","level","pubtime");public
function
__construct(){}}class
ntssi_contact
extends
TblObj{public$Fd=0;public$xd="";public$La="";public$gj="";public$hf="";public$Gs="";public$vq="";public$wq="";public$Ie="";public$zr="";public$vg="";public$wg="";public$xg="";public$u="";public$l="";public$c="contact_id";public$b=array("contact_id","companyname","address","lxr","fax","zc","tel_one","tel_two","email","url","hz1","hz2","hz3","idate","content");public
function
__construct(){}}class
ntssi_count
extends
TblObj{public$Vc=0;public$Gh="";public$ps="";public$c="cid";public$b=array("cid","ip","visitdate");public
function
__construct(){}}class
ntssi_discountgoods
extends
TblObj{public$ze=0;public$Ge=0;public$r=0;public$Ym=0;public$Hd=0;public$Jg=0;public$c="dgid";public$b=array("dgid","dsid","gid","price","cost","ifcheck");public
function
__construct(){}}class
ntssi_discountsubject
extends
TblObj{public$Ge=0;public$eq="";public$Lp="";public$Me="";public$Rj=0;public$Qj=0;public$gq=0;public$bq="";public$Nj=0;public$xq="";public$io="";public$qm=0;public$Lo=0;public$Tq=0;public$wc=0;public$c="dsid";public$b=array("dsid","subject_name","start_date","end_date","min_money","min_count","subject_open","subject_content","mianyunfei","template","remark","point","saleoff","total","buycount");public
function
__construct(){}}class
ntssi_edmsmg
extends
TblObj{public$Gn=0;public$In="";public$Hn="";public$Fn="";public$En="";public$Dn=0;public$c="publication_id";public$b=array("publication_id","publication_title","publication_start_time","publication_end_time","publication_content","publication_alreadysend");public
function
__construct(){}}class
ntssi_excel_ps
extends
TblObj{public$t=0;public$yn="";public$c="id";public$b=array("id","ps");public
function
__construct(){}}class
ntssi_falsemail
extends
TblObj{public$mj="";public$om=0;public$Ck=0;public$kp="";public$t=0;public$c="id";public$b=array("mail","pid","no","sendtime","id");public
function
__construct(){}}class
ntssi_falsesmg
extends
TblObj{public$uq="";public$om=0;public$Ck=0;public$kp="";public$t=0;public$c="id";public$b=array("tel","pid","no","sendtime","id");public
function
__construct(){}}class
ntssi_forum_affiche
extends
TblObj{public$tf=0;public$gb="";public$eb="";public$Np=0;public$zg=0;public$sm=0;public$Rr="";public$fb="";public$c="forum_affiche_id";public$b=array("forum_affiche_id","affiche_title","affiche_content","state","iconid","points","username","affiche_idate");public
function
__construct(){}}class
ntssi_forum_class
extends
TblObj{public$ac=0;public$S=0;public$Gc="";public$Hc=0;public$Ec=0;public$zh="";public$l="";public$Jb="";public$Ib="";public$c="bid";public$b=array("bid","top_id","catname","catord","catiffb","intro","content","attr_id","attr");public
function
__construct(){}}class
ntssi_forum_post
extends
TblObj{public$Gm=0;public$Mq=0;public$Sq=0;public$Jq="";public$l="";public$Nb="";public$u="";public$Hi="";public$U=0;public$c="post_id";public$b=array("post_id","topclass_id","toppost_id","title","content","author","idate","lidate","user_id");public
function
__construct(){}}class
ntssi_forum_toppost
extends
TblObj{public$Sq=0;public$Mq=0;public$yg=0;public$Qq="";public$Oq="";public$yi="";public$wi="";public$vi=0;public$_i="";public$Cn=0;public$po=0;public$gs=0;public$Np=0;public$Pq="";public$c="toppost_id";public$b=array("toppost_id","topclass_id","icon","topost_title","topost_author","lastmember","lastidate","lastid","lasttitle","public","revert","view","state","topost_idate");public
function
__construct(){}}class
ntssi_forum_vol
extends
TblObj{public$qs=0;public$rs="";public$c="vloid";public$b=array("vloid","volname");public
function
__construct(){}}class
ntssi_forumsession
extends
TblObj{public$Bp=0;public$qp="";public$Pr=0;public$Gh="";public$zi="";public$c="sid";public$b=array("sid","sessionid","userid","ip","lasttime");public
function
__construct(){}}class
ntssi_good_comment
extends
TblObj{public$rd=0;public$Lf=0;public$pd="";public$od="";public$pb=0;public$sd="";public$Jg=0;public$c="comment_id";public$b=array("comment_id","good_id","comment_content","comment_answer","already_read","comment_idate","ifcheck");public
function
__construct(){}}class
ntssi_good_link
extends
TblObj{public$Mf=0;public$Gl=0;public$wo=0;public$Qi=0;public$u="";public$Js=0.0;public$c="good_link_id";public$b=array("good_link_id","p_gid","s_gid","link_type","idate","zk_price");public
function
__construct(){}}class
ntssi_good_pic
extends
TblObj{public$Rf=0;public$Lf=0;public$Sf="";public$Tf="";public$Qf="";public$c="goodpic_id";public$b=array("goodpic_id");public
function
__construct(){}}class
ntssi_goodcolor
extends
TblObj{public$t=0;public$Lf=0;public$jd="";public$mm="";public$nm="";public$c="id";public$b=array("id","good_id","color","pic1","pic2");public
function
__construct(){}}class
ntssi_goods
extends
TblObj{public$r=0;public$Yf="";public$ac=0;public$yr=0;public$gc="";public$zh="";public$oc="";public$pc=0;public$xr="";public$Zm=0;public$D=0;public$Ym=0;public$qm=0;public$kb=0;public$jb="";public$Dk=0;public$kc=0;public$cq="";public$Ko=0;public$Up=0;public$Dg=0;public$Zg=0;public$ah=0;public$ih=0;public$Hg=0;public$Pg=0;public$Mg=0;public$Rg=0;public$Uh=NULL;public$Vh=NULL;public$Wh="";public$Xh=0;public$Vg=0;public$Gf="";public$Pj="";public$Gp="";public$dc="";public$Of="";public$Jf="";public$Nf="";public$Pf=0;public$hs=0;public$wf="";public$xf="";public$ri="";public$fs="";public$sq="";public$hc="";public$u="";public$Bg=0;public$Hd=0;public$Yg=0;public$Tm=0;public$bh=0;public$qi="";public$Je="";public$yd="";public$Cc="";public$Bc="";public$ar=0;public$Yq=0;public$lh=0;public$Zq=0;public$nh=0;public$mh=0;public$oh=0;public$Ig=0;public$xs=0;public$Ao="";public$Zf="";public$Co=0;public$Bo=0;public$eh=0;public$dh=0;public$No="";public$Mo="";public$Cg=0;public$Ia=0;public$Ja=0;public$Tk="";public$Oo=0;public$jh=0;public$Iq=0;public$Hq=0;public$Yh="";public$Sm=0;public$ir=0;public$Ug=0;public$Na=0;public$jr=0;public$Jo="";public$Ej=0;public$ld=0;public$Qc=0;public$kh=0;public$og="";public$ws="";public$zp=0;public$xp=0;public$ts=0.0;public$Og=0;public$Ek="";public$Eo=0;public$ak="";public$vb="";public$sb="";public$Gg=0;public$tb=0;public$ub=0;public$Jc="";public$ca="";public$Yb=0;public$Zb="";public$ro=0;public$so="";public$Sg=0;public$up="";public$Qo="";public$Jn="";public$Bn="";public$jc="";public$ic="";public$vk="";public$tk="";public$uk=0;public$bl=0;public$Kf="";public$c="gid";public$b=array("gid","upbid","brand_id","provider_id","point","alarmnum","alarmcontent","nocarriage","bonusnum","subject_id","salenum","ifbonus","ifjs","js_begtime","js_endtime","js_price","js_totalnum","gimg","middleimg","smallimg","bigimg","good_color","good_size","goodorder","view_num","if_monthprice","cost","ifpresent","present_money","ifrecommend_man","en_name","component","capability","trans_type","trans_special","iftransabroad","trans_special_money","ifxygoods","ifxy","ifxysale","ifchange","xycount","goodsno","sale_subject","sale_price","ifsales","ifsaleoff","saleoff_starttime","saleoff_endtime","ifadd","addmoney","addprice","oeid","saleoffprice","iftimesale","timesale_starttime","timesale_endtime","present_endmoney","transtype","ifmood","addtransmoney","transtypemonty","memberprice","combipoint","checkstate","iftogether","guojima","xinghao","shopid","shopclass","weight","ifhome","nocheckreason","salecost","month","appoint_starttime","appoint_endtime","ifappoint","appoint_send","appoint_sendtype","chandi","ERP","baozhuang1","baozhuang2","rongliang1","rongliang2","iflengcang","shangwei","salepic","pubstarttime","pubendtime","bonus_statetime","bonus_endtime","newuser_starttime","newuser_endtime","newuser_price","olduser_price","good_color_pic");public
function
__construct(){$this->js_begtime=new
DateTime();$this->js_endtime=new
DateTime();}}class
ntssi_goods_change
extends
TblObj{public$Lc=0;public$r=0;public$Kc=0;public$Ym=0;public$u="";public$c="changeid";public$b=array("changeid","gid","changegid","price","idate");public
function
__construct(){}}class
ntssi_goods_class
extends
TblObj{public$t=0;public$r=0;public$ac=0;public$c="id";public$b=array("id","gid","bid");public
function
__construct(){}}class
ntssi_goods_detail
extends
TblObj{public$re=0;public$r=0;public$se="";public$oe="";public$we=0;public$xe=0;public$qe="";public$ve="";public$E="";public$Up=0;public$pe=0;public$c="detail_id";public$b=array("detail_id","gid","detail_price","detail_pricedes","storage","detail_cost");public
function
__construct(){}}class
ntssi_goods_saleoffe
extends
TblObj{public$Ip=0;public$r=0;public$Sj=0;public$xj=0;public$Ym=0;public$c="soid";public$b=array("soid","gid","mincount","maxcount","price");public
function
__construct(){}}class
ntssi_goods_tag
extends
TblObj{public$mg=0;public$r=0;public$qq=0;public$c="gtid";public$b=array("gtid","gid","tagid");public
function
__construct(){}}class
ntssi_goods_userlevel
extends
TblObj{public$ng=0;public$r=0;public$Fi=0;public$c="guid";public$b=array("guid","gid","levelid");public
function
__construct(){}}class
ntssi_goods_xy
extends
TblObj{public$Cs=0;public$r=0;public$ys=0;public$u="";public$c="xyid";public$b=array("xyid","gid","xygid","idate");public
function
__construct(){}}class
ntssi_goodscollection
extends
TblObj{public$zf=0;public$Af="";public$Bf="";public$Cf="";public$_f="";public$pq="";public$gh=0;public$c="gc_id";public$b=array("gc_id","gc_name","gc_pic","gc_string","ifshop");public
function
__construct(){}}class
ntssi_group_pic
extends
TblObj{public$Rf=0;public$Lf=0;public$Sf="";public$Tf="";public$Qf="";public$c="goodpic_id";public$b=array("goodpic_id");public
function
__construct(){}}class
ntssi_group_saleoffe
extends
TblObj{public$Ip=0;public$Df=0;public$Sj=0;public$xj=0;public$Lo=0;public$Ej=0;public$ig=0;public$c="soid";public$b=array("soid","gdid","mincount","maxcount","saleoff","memberprice","grouppoint");public
function
__construct(){}}class
ntssi_groupclass
extends
TblObj{public$ac=0;public$S=0;public$Gc="";public$Fc="";public$Dc="";public$Hc=0;public$Ec=0;public$Ib="";public$mm="";public$nm="";public$vf=0;public$Hj="";public$Ij="";public$Og=0;public$Il=0;public$Wb="";public$Xb="";public$ok=0;public$Ki="";public$Lo=0;public$On=0;public$Id=0;public$cq="";public$c="bid";public$b=array("bid","top_id","catname","catord","catiffb","gain","ifhome","parent_id","banner","banner2","nclass","link","saleoff","rebate","costrebate","subject_id");public
function
__construct(){}}class
ntssi_groupdetail
extends
TblObj{public$Df=0;public$hg="";public$fg="";public$kg=0;public$ig=0;public$ag="";public$cg="";public$bg="";public$dg="";public$l="";public$Xf="";public$E="";public$Zg=0;public$hs=0;public$ah=0;public$xm="";public$Io="";public$ac=0;public$Ym=0;public$zh="";public$Pg=0;public$Qc=0;public$Ek="";public$Ej=0;public$Hd=0;public$ts=0;public$Ep="";public$xr="";public$ne="";public$No="";public$Mo="";public$dh=0;public$io="";public$c="gdid";public$b=array("gdid","groupname","groupbn","groupprice","grouppoint","groupBimg","groupSimg","groupMimg","groupVidio","content","goodslist","pubtime","ifpub","view_num","ifrecommend","poscode","salename","bid","price","ifhot","checkstate","nocheckreason","memberprice","cost","weight","size","unit","des","saleoff_starttime","saleoff_endtime","ifsaleoff","remark");public
function
__construct(){}}class
ntssi_groupgoods
extends
TblObj{public$Ff=0;public$lg=0;public$r=0;public$Ym=0;public$Hd=0;public$Jg=0;public$ig=0;public$c="ggid";public$b=array("ggid","gsid","gid","price","cost","ifcheck","grouppoint");public
function
__construct(){}}class
ntssi_grouppoint
extends
TblObj{public$t=0;public$qm=0;public$U=0;public$Ma="";public$Oe="";public$Ur=0;public$l="";public$zl=0;public$yo=0;public$zo=0;public$c="id";public$b=array("id","point","user_id","addtime","endtime","usestate","content","orderid","sa_id","sa_type");public
function
__construct(){}}class
ntssi_grouppointbuydetail
extends
TblObj{public$t=0;public$U=0;public$l="";public$jg=0;public$Dr=0;public$Vr="";public$zl=0;public$eg=0;public$yo=0;public$zo=0;public$c="id";public$b=array("id","user_id","content","grouppoint_id","usepoint","usetime","orderid","group_id","sa_id","sa_type");public
function
__construct(){}}class
ntssi_groupsubject
extends
TblObj{public$lg=0;public$eq="";public$Lp="";public$Me="";public$Rj=0;public$Qj=0;public$gq=0;public$bq="";public$xq="";public$io="";public$ig=0;public$qj=0;public$xc=0;public$lm="";public$ah=0;public$c="gsid";public$b=array("gsid","subject_name","start_date","end_date","min_money","min_count","subject_open","subject_content","template","remark","grouppoint","manyunfei","buygrouppoint","pic","ifrecommend");public
function
__construct(){}}class
ntssi_image
extends
TblObj{public$ph=0;public$om=0;public$l="";public$lm="";public$c="iid";public$b=array("iid","pid","content","pic");public
function
__construct(){}}class
ntssi_kefu
extends
TblObj{public$si=0;public$uj="";public$op="";public$or="";public$pr="";public$U=0;public$Rr="";public$Nn="";public$Ie="";public$Qm=0;public$Jq="";public$ui=0;public$Sp=0;public$Tg=0;public$di="";public$Pc=0;public$sl="";public$D=0;public$oi="";public$Tj="";public$c="kid";public$b=array("kid","marketno","serialnum","type_chuli","type_chuli_name","user_id","username","realname","email","postnum","title","lastdate","status","iflogin","k_kefu_con","checked","order_serial","provider_id","kefu_type","mobile");public
function
__construct(){}}class
ntssi_kefu_chuli
extends
TblObj{public$bi=0;public$Sp=0;public$ci="";public$Pc=0;public$Kg=0;public$c="k_chuli_id";public$b=array("k_chuli_id","status","k_chuli_name","checked","ifclose");public
function
__construct(){}}class
ntssi_kefu_log
extends
TblObj{public$Vi=0;public$ni=0;public$U=0;public$Tr=0;public$l="";public$E="";public$c="log_id";public$b=array("log_id","kefu_id","user_id","usertype","content","pubtime");public
function
__construct(){}}class
ntssi_kefu_posts
extends
TblObj{public$fi=0;public$si=0;public$Rr="";public$Ie="";public$Pm=0;public$gi="";public$ei="";public$sl="";public$D=0;public$Jg=0;public$c="k_post_id";public$b=array("k_post_id","kid","username","email","postdate","k_post_title","k_post_con","order_serial","provider_id","ifcheck");public
function
__construct(){}}class
ntssi_kefu_tem
extends
TblObj{public$ii=0;public$Sp=0;public$ji="";public$hi="";public$Pc=0;public$c="k_tem_id";public$b=array("k_tem_id","status","k_tem_name","k_tem_con","checked");public
function
__construct(){}}class
ntssi_kefu_type
extends
TblObj{public$li=0;public$Sp=0;public$mi="";public$ki="";public$Pc=0;public$rr=0;public$c="k_type_id";public$b=array("k_type_id","status","k_type_name","k_type_content","checked","typegroup");public
function
__construct(){}}class
ntssi_link
extends
TblObj{public$Ni=0;public$Pi="";public$Si=0;public$Mi=0;public$Ri="";public$Li=0;public$Oi="";public$xl=0;public$c="link_id";public$b=array("link_id","link_title","link_width","link_height","link_url","link_display","link_ima","orderby");public
function
__construct(){}}class
ntssi_login_log
extends
TblObj{public$Vi=0;public$cj="";public$bj="";public$Zi="";public$aj="";public$c="log_id";public$b=array("log_id","loginuser","logintype","loginip","logintime");public
function
__construct(){}}class
ntssi_mail_group
extends
TblObj{public$Kj=0;public$Mj="";public$Ob=0;public$Lj="";public$c="mgroup_id";public$b=array("mgroup_id","mgroup_name","auto","mgroup_list");public
function
__construct(){}}class
ntssi_member_price
extends
TblObj{public$lj=0;public$jj=0;public$ij=0;public$kj=0;public$hj=0;public$c="m_price_id";public$b=array("m_price_id","m_level_id","m_goods_id","m_detail_id");public
function
__construct(){}}class
ntssi_menu_right
extends
TblObj{public$ck=0;public$Jq="";public$Hl="";public$lm="";public$Bi=0;public$hh=0;public$c="mrid";public$b=array("mrid","level","ifshow");public
function
__construct(){}}class
ntssi_month_price
extends
TblObj{public$lj=0;public$Uf=0;public$ak=0;public$bk=0.0;public$c="m_price_id";public$b=array("m_price_id","goods_id","month","month_price");public
function
__construct(){}}class
ntssi_msgconfig
extends
TblObj{public$t=0;public$Gh="";public$vm=0;public$Er="";public$Ml="";public$c="id";public$b=array("id","ip","port","user","password");public
function
__construct(){}}class
ntssi_nclass
extends
TblObj{public$mk=0;public$pk="";public$S=0;public$lk=0;public$nk="";public$kk=0;public$Yc=0;public$yq=0;public$Lg=0;public$c="ncid";public$b=array("ncid","ncname","top_id","ncatord","ncimg","ncatiffb","classid","templatetype","ifcomment");public
function
__construct(){}}class
ntssi_news
extends
TblObj{public$sk=0;public$S=0;public$Jk="";public$Kk="";public$Ak="";public$Bk="";public$Nb="";public$zr="";public$_r=0;public$Fk=0;public$zk=0;public$tc="";public$jk="";public$yk="";public$_k="";public$An=NULL;public$js=0;public$c="news_id";public$b=array("news_id","top_id","ntitle","ntitle_color","nltitle","nltitle_color","author","url","url_on","nord","niffb","brief","nbody","nidate","nimg","pubdate","viewnum");public
function
__construct(){$this->pubdate=new
DateTime();}}class
ntssi_news_comment
extends
TblObj{public$rd=0;public$xk=0;public$pd="";public$od="";public$pb=0;public$sd="";public$c="comment_id";public$b=array("comment_id","nid","comment_content","comment_answer","already_read","comment_idate");public
function
__construct(){}}class
ntssi_news_link
extends
TblObj{public$Ni=0;public$r=0;public$xk=0;public$u="";public$c="link_id";public$b=array("link_id","gid","nid","idate");public
function
__construct(){}}class
ntssi_news_userlevel
extends
TblObj{public$Lk=0;public$xk=0;public$Fi=0;public$c="nuid";public$b=array("nuid","nid","levelid");public
function
__construct(){}}class
ntssi_offhand
extends
TblObj{public$Uk=0;public$T="";public$_a="";public$c="of_id";public$b=array("of_id");public
function
__construct(){}}class
ntssi_operater
extends
TblObj{public$il=0;public$Rr="";public$Sr="";public$mr="";public$cn="";public$Sp=0;public$xi=0;public$T=0;public$Ie="";public$gg=0;public$c="opid";public$b=array("opid","username","userpass","privilege","status","lastlogin","type","email","groupid");public
function
__construct(){}}class
ntssi_operater_class
extends
TblObj{public$t=0;public$il=0;public$ac=0;public$c="id";public$b=array("id","opid","bid");public
function
__construct(){}}class
ntssi_operatergroup
extends
TblObj{public$il=0;public$hg="";public$cn="";public$c="opid";public$b=array("opid","groupname","privilege");public
function
__construct(){}}class
ntssi_order_action
extends
TblObj{public$Ga=0;public$C=0;public$Rp=0;public$U=0;public$Tr=0;public$Jg=0;public$io="";public$Ha="";public$Pp=0;public$ol=0;public$Qb=0;public$c="action_id";public$b=array("action_id","order_id","state_value","user_id","usertype","ifcheck","remark","actiontime","state_type","order_detail_id","backprice");public
function
__construct(){}}class
ntssi_order_detail
extends
TblObj{public$ol=0;public$r=0;public$C=0;public$ue=0;public$te=0;public$pg=0;public$xr="";public$qm=0;public$Yf="";public$D=0;public$Wf=0;public$Jf="";public$Nf="";public$tj=0.0;public$Ym=0.0;public$ak=0;public$re=0;public$oe="";public$se="";public$qe="";public$zs="";public$nh=0;public$Ig=0;public$As="";public$_s="";public$Bs="";public$Tk="";public$jm="";public$Oc="";public$Dj=0;public$Ej=0;public$ld=0;public$ye=0;public$Hg=0;public$lc=0;public$gc="";public$kh=0;public$Hd=0;public$Do="";public$ql=0;public$c="order_detail_id";public$b=array("order_detail_id","gid","order_id","detail_pay_state","detail_order_state","hadsend","unit","point","goodsname","provider_id","goodscount","good_color","good_size","market_price","price","month","ifxygoods","ifchange","oeid","memberorprice","memberprice","combipoint","detail_transport_state","ifbonus","bonuspoint","bn","iftogether","cost","salecontent","order_group_id");public
function
__construct(){}}class
ntssi_order_group
extends
TblObj{public$ql=0;public$Df=0;public$C=0;public$hg="";public$Jd=0;public$kg=0.0;public$ig=0.0;public$fg="";public$Xf="";public$aq=0;public$hq="";public$pg=0;public$Hd=0;public$D=0;public$c="order_group_id";public$b=array("order_group_id","gdid","order_id","groupname","count","groupprice","grouppoint","groupbn","goodslist","subject","subjectcontent","hadsend","cost","provider_id");public
function
__construct(){}}class
ntssi_order_state
extends
TblObj{public$ul=0;public$vl="";public$Jg=0;public$Pp=0;public$Rp=0;public$Um="";public$oj=0;public$Kl=0;public$c="order_state_id";public$b=array("order_state_id","order_state_name","ifcheck","state_type","state_value","previous_state","mailno","partstate");public
function
__construct(){}}class
ntssi_order_table
extends
TblObj{public$C=0;public$U=0;public$sl="";public$Xn="";public$Tn="";public$Un="";public$Yn="";public$Zn="";public$Wn="";public$Vn="";public$er="";public$br="";public$Fh="";public$Ch=0;public$Hb="";public$Qg=0;public$Wq=0.0;public$Zl=0;public$el=0;public$fl=0;public$dl=0;public$am="";public$le=0;public$me="";public$wl="";public$rl="";public$nl="";public$tl=0;public$D=0;public$Tl=0;public$gr=0;public$ml=0;public$kl=NULL;public$ll="";public$Xl="";public$kp="";public$Md="";public$Bq=0;public$Cq=0;public$Aq="";public$lc=0;public$Fe=0;public$_q=0;public$So="";public$Vq=0;public$jm="";public$qo="";public$ao="";public$fr=0;public$kh=0;public$zp=0;public$Pd="";public$Qd="";public$ip=0;public$Ah="";public$Yp=0;public$hp="";public$ka="";public$Bh="";public$Ng=0;public$Uq=0;public$Hf=0;public$uc=0;public$He="";public$Gq="";public$Eg=0;public$Jp=0;public$Wk="";public$Vk="";public$eo=0;public$c="order_id";public$b=array("order_id","user_id","order_serial","receiver_name","receiver_address","receiver_email","receiver_post","receiver_tele","receiver_mobile","receiver_memo","transport_price","transport_content","invoiceform","invoice_num","atm","ifinvoice","totalprice","paymentid","online_paytype","onlinepay","online_cardnum","paymentname","deliveryid","deliveryname","order_year","order_month","order_day","order_state","provider_id","pay_state","transtime_id","order007_status","order007_begtime","paycontent","sendtime","createtime","ticketid","ticketmoney","bonuspoint","discount_totalPrices","ticket_discount_money","totalbonuspoint","piaocode","rid","recommendno","transport_state","iftogether","shopid","cvsname","cvsnum","sendpoint","invoice_code","store_id","sendname","MallgicOrderId","invoice_date","ifgroup","totalGrouppoint","giveGroup","buyPoint","duedate","timepaid","ifalert","sp_ordermultiple","okmap","okgo_code","refundtype");public
function
__construct(){$this->order007_begtime=new
DateTime();}}class
ntssi_order_userback
extends
TblObj{public$Mr=0;public$Or=0;public$Lr=0;public$Nr="";public$D=0;public$U=0;public$C=0;public$Ir="";public$kq="";public$c="userback_id";public$b=array("userback_id","userback_type","userback_alread","userback_idate","provider_id","user_id","order_id","user_say","sys_say");public
function
__construct(){}}class
ntssi_ordermail
extends
TblObj{public$cl=0;public$C=0;public$pj=0;public$kp=0;public$Xd=0;public$c="omid";public$b=array("omid","order_id","mailtype","sendtime","days");public
function
__construct(){}}class
ntssi_pay_state
extends
TblObj{public$Ul=0;public$Wl=0;public$Vl="";public$c="pay_state_id";public$b=array("pay_state_id","pay_state_value","pay_state_name");public
function
__construct(){}}class
ntssi_pay_type
extends
TblObj{public$Rl=0;public$Sl="";public$Tl=0;public$Ql="";public$c="pay_id";public$b=array("pay_id","pay_name","pay_state","pay_content");public
function
__construct(){}}class
ntssi_paymanager
extends
TblObj{public$om=0;public$cm="";public$l="";public$yp="";public$Ye="";public$Ze="";public$af="";public$bf="";public$cf="";public$ak=0;public$fm="";public$no="";public$oo="";public$em=0;public$c="pid";public$b=array("pid","month","paytype");public
function
__construct(){}}class
ntssi_paymethod
extends
TblObj{public$Oj=0;public$Jj="";public$l="";public$dm="";public$om=0;public$Xg=0;public$ak=0;public$c="mid";public$b=array("mid","pid","ifopen","month");public
function
__construct(){}}class
ntssi_photo
extends
TblObj{public$t=0;public$ik="";public$E="";public$Yc=0;public$l="";public$T=0;public$rf="";public$ti="";public$An="";public$c="id";public$b=array("id","name","pubtime","classid","type");public
function
__construct(){}}class
ntssi_photoclass
extends
TblObj{public$t=0;public$ik="";public$c="id";public$b=array("id","name");public
function
__construct(){}}class
ntssi_poll
extends
TblObj{public$tm=0;public$Jq="";public$um=0;public$gl=0;public$u="";public$T=0;public$c="poll_id";public$b=array("poll_id","title","polloptionnum","open","idate","type");public
function
__construct(){}}class
ntssi_poll_option
extends
TblObj{public$iq=0;public$tm=0;public$jq="";public$sm=0;public$c="subpoll_id";public$b=array("subpoll_id","poll_id","subtitle","points");public
function
__construct(){}}class
ntssi_posts
extends
TblObj{public$ga=0;public$zm=0;public$Dm=NULL;public$Em=NULL;public$Am="";public$Nm="";public$_m=0;public$Fm="";public$Mm="";public$Km="";public$Lq="";public$pm="";public$Im=NULL;public$Jm=NULL;public$Bm="";public$Lm=0;public$ng="";public$Fj=0;public$Om="";public$Hm="";public$qd=0;public$c="ID";public$b=array("ID","post_author","post_date","post_date_gmt","post_content","post_title","post_category","post_excerpt","post_status","comment_status","ping_status","post_password","post_name","to_ping","pinged","post_modified","post_modified_gmt","post_content_filtered","post_parent","guid","menu_order","post_type","post_mime_type","comment_count");public
function
__construct(){$this->post_date=new
DateTime();$this->post_date_gmt=new
DateTime();$this->post_modified=new
DateTime();$this->post_modified_gmt=new
DateTime();}}class
ntssi_provider
extends
TblObj{public$D=0;public$mn="";public$tn="";public$sn="";public$fn="";public$jn="";public$kn="";public$gn=0;public$dn="";public$en="";public$hn="";public$in="";public$Vb="";public$Tb="";public$Rb="";public$Fs=0;public$Nj=0;public$ug=0;public$wn="";public$rc="";public$Xj="";public$km="";public$la=0;public$Lp="";public$Me="";public$Np=0;public$Yl="";public$ib="";public$hf="";public$ss="";public$Qn="";public$Rn="";public$Sn="";public$Aa="";public$Da="";public$Ca="";public$Ba="";public$ln="";public$Ub="";public$Ch="";public$Dh="";public$_h="";public$un=0;public$em="";public$vd="";public$gf="";public$qj=0;public$c="provider_id";public$b=array("provider_id","provider_name","provider_thenum","provider_tel","provider_email","provider_loginpassword","provider_lxr","provider_fb","provider_addr","provider_content","provider_idate","provider_lastlogin","yunfei","mianyunfei","huodaofukuan","providerno","brandname","mode","piaoqi","PM","start_date","end_date","state","payment","agreementno","fax","websit","receive_mail1","receive_mail2","receive_mail3","account_lxr","account_tel","account_mobile","account_mail","provider_mobile","bankno","invoice_num","invoice_title","invoice_addr","provider_type","paytype","company_tel","fanid","manyunfei");public
function
__construct(){}}class
ntssi_provider_month
extends
TblObj{public$Oj=0;public$om=0;public$Es=0;public$ak=0;public$Yj=0;public$jl=0;public$_o=0;public$kh=0;public$Eh="";public$Wg=0;public$bm=0;public$sj="";public$Hs=0;public$c="mid";public$b=array("mid","pid","year","month","money","optime","said","iftogether","invoice_titles","ifok","paymoney","mark","zhang");public
function
__construct(){}}class
ntssi_provider_news
extends
TblObj{public$pn=0;public$rn="";public$vn=0;public$on=0;public$nn="";public$qn="";public$D=0;public$c="provider_nid";public$b=array("provider_nid","provider_ntitle","provider_who","provider_nfb","provider_ncontent","provider_nidate","provider_id");public
function
__construct(){}}class
ntssi_publication
extends
TblObj{public$Gn=0;public$In="";public$Hn="";public$Fn="";public$En="";public$Dn=0;public$c="publication_id";public$b=array("publication_id","publication_title","publication_start_time","publication_end_time","publication_content","publication_alreadysend");public
function
__construct(){}}class
ntssi_receiver
extends
TblObj{public$ho=0;public$Xn="";public$Un="";public$ym="";public$Ld="";public$xn="";public$Xc="";public$Ka="";public$Zn="";public$Wn="";public$U=0;public$c="reid";public$b=array("reid","user_id");public
function
__construct(){}}class
ntssi_sale_subject
extends
TblObj{public$cq=0;public$eq="";public$gq=0;public$bq="";public$fq=0;public$Fo=0;public$c="subject_id";public$b=array("subject_id","subject_name","subject_open","subject_content","subject_num","salecount");public
function
__construct(){}}class
ntssi_saler
extends
TblObj{public$t=0;public$ik="";public$Ml="";public$uq="";public$Ka="";public$Ie="";public$Vb="";public$Tb="";public$Rb="";public$Zg=0;public$Xi="";public$E="";public$To=0;public$hl="";public$Qr=0;public$If=0;public$ud="";public$Jl="";public$Ed="";public$c="id";public$b=array("id","name","password","tel","addr","email","bankuser","bankname","bank","ifpub","login","pubtime","salerset","openpwd","userlevel","givebouns","company","partment","contact");public
function
__construct(){}}class
ntssi_salermoney
extends
TblObj{public$t=0;public$To=0;public$c="id";public$b=array("id","salerset");public
function
__construct(){}}class
ntssi_saletotal
extends
TblObj{public$Uo=0;public$r=0;public$Ho="";public$Ko=0;public$Go=NULL;public$c="saletotal_id";public$b=array("saletotal_id","gid","salemoney","saledate");public
function
__construct(){$this->saledate=new
DateTime();}}class
ntssi_score
extends
TblObj{public$cp=0;public$Zo=0;public$ap=0;public$bp=0;public$zp=0;public$C=0;public$U=0;public$dp="";public$r=0;public$l="";public$rb="";public$c="score_id";public$b=array("score_id","score1","score2","score3","shopid","order_id","user_id","scoretime","gid","content","answer");public
function
__construct(){}}class
ntssi_sendmsg
extends
TblObj{public$np=0;public$hp="";public$lp="";public$jp=0;public$mp="";public$gp="";public$c="sendtype_id";public$b=array("sendtype_id","sendname","sendtitle","sendstatus","sendtype","sendcontent");public
function
__construct(){}}class
ntssi_sendtype
extends
TblObj{public$np=0;public$hp="";public$lp="";public$jp=0;public$mp="";public$gp="";public$c="sendtype_id";public$b=array("sendtype_id","sendname","sendtitle","sendstatus","sendtype","sendcontent");public
function
__construct(){}}class
ntssi_session_table
extends
TblObj{public$t=0;public$pp="";public$yo=0;public$T=0;public$c="id";public$b=array("id","session_id","sa_id","type");public
function
__construct(){}}class
ntssi_shopbclass
extends
TblObj{public$ac=0;public$S=0;public$Gc="";public$Fc="";public$Dc="";public$Hc=0;public$Ec=0;public$Ib="";public$mm="";public$nm="";public$vf=0;public$Hj="";public$Ij="";public$Og=0;public$Il=0;public$Wb="";public$Xb="";public$ok=0;public$Ki="";public$Lo=0;public$c="bid";public$b=array("bid","top_id","catname","catord","catiffb","gain","ifhome","parent_id","banner","banner2","nclass","link","saleoff");public
function
__construct(){}}class
ntssi_shopclass
extends
TblObj{public$Yo=0;public$S=0;public$Zc="";public$zp=0;public$c="scid";public$b=array("scid","top_id","classname","shopid");public
function
__construct(){}}class
ntssi_shopcomment
extends
TblObj{public$Yo=0;public$Nq=0;public$vr=0;public$l="";public$E="";public$zp=0;public$c="scid";public$b=array("scid","topid","uid","content","pubtime","shopid");public
function
__construct(){}}class
ntssi_shopgoodsclass
extends
TblObj{public$sp=0;public$S=0;public$Zc="";public$zp=0;public$c="sgcid";public$b=array("sgcid","top_id","classname","shopid");public
function
__construct(){}}class
ntssi_shopinfo
extends
TblObj{public$Bp=0;public$_p="";public$l="";public$vc="";public$Db="";public$Ap="";public$vr=0;public$E="";public$Np=0;public$xp=0;public$Nj=0;public$ah=0;public$Rr="";public$Ml="";public$gj="";public$uq="";public$Tj="";public$hf="";public$Ka="";public$Ie="";public$vp="";public$wp="";public$Pa="";public$Pg=0;public$dj="";public$hs=0;public$gf="";public$c="sid";public$b=array("sid","shopname","content","buycontent","askcontent","shoppic","uid","pubtime","state","shopclass","mianyunfei","ifrecommend","username","password","lxr","tel","mobile","fax","addr","email","shop_description","shop_keywords","adv","ifhot","logo","view_num","fanid");public
function
__construct(){}}class
ntssi_shopnews
extends
TblObj{public$Hp=0;public$Jq="";public$l="";public$E="";public$zp=0;public$c="snid";public$b=array("snid","title","content","pubtime","shopid");public
function
__construct(){}}class
ntssi_storage
extends
TblObj{public$Vp=0;public$jd="";public$Ep="";public$Uf=0;public$Up=0;public$c="storage_id";public$b=array("storage_id","color","size","goods_id","storage");public
function
__construct(){}}class
ntssi_storagelog
extends
TblObj{public$Fp=0;public$r=0;public$re=0;public$U=0;public$Mc=0;public$Kd=0;public$Kr=0;public$l="";public$Wp=0;public$Vp=0;public$Wd="";public$C=0;public$Ob=0;public$c="slid";public$b=array("slid","gid","detail_id","user_id","changes","counts","user_type","content","storagetype","storage_id","datetime","order_id","auto");public
function
__construct(){}}class
ntssi_store
extends
TblObj{public$Yp=0;public$Zp="";public$Xp="";public$xn="";public$Xc="";public$La="";public$uq="";public$rj="";public$c="store_id";public$b=array("store_id","store_name","store_code","province","city","address","tel","map");public
function
__construct(){}}class
ntssi_study
extends
TblObj{public$t=0;public$U=0;public$Jq="";public$T=0;public$sg=0;public$rg=0;public$l="";public$pf="";public$Zg=0;public$An="";public$Pc=0;public$c="id";public$b=array("id","user_id","title","type","hiddenschool","hiddenname","content","filename","ifpub","pubdate","checked");public
function
__construct(){}}class
ntssi_studytype
extends
TblObj{public$t=0;public$ik="";public$c="id";public$b=array("id","name");public
function
__construct(){}}class
ntssi_subject
extends
TblObj{public$cq=0;public$eq="";public$gq=0;public$bq="";public$fq=0;public$c="subject_id";public$b=array("subject_id","subject_name","subject_open","subject_content","subject_num");public
function
__construct(){}}class
ntssi_sysmail
extends
TblObj{public$t=0;public$mj="";public$T="";public$c="id";public$b=array("id","mail");public
function
__construct(){}}class
ntssi_tag
extends
TblObj{public$qq=0;public$rq="";public$Jd=0;public$Wf=0;public$Ab=0;public$is=0;public$c="tagid";public$b=array("tagid");public
function
__construct(){}}class
ntssi_ticket
extends
TblObj{public$Bq=0;public$Dq="";public$Aq="";public$Yj=0.0;public$_n="";public$zn="";public$Br="";public$Ar="";public$T=0;public$Zj=0;public$Vf="";public$Al=0;public$c="ticketid";public$b=array("ticketid","ticketname","ticketcode","money","pub_starttime","pub_endtime","use_starttime","use_endtime","type","moneytype","ordertotal");public
function
__construct(){}}class
ntssi_ticketcode
extends
TblObj{public$ed=0;public$Bq=0;public$Aq="";public$Vr="";public$Pr=0;public$c="codeid";public$b=array("codeid","ticketid","ticketcode");public
function
__construct(){}}class
ntssi_ticketpubrecord
extends
TblObj{public$bo=0;public$Bq=0;public$T=0;public$l="";public$Jd=0;public$E="";public$c="recordid";public$b=array("recordid","ticketid","type","content","count","pubtime");public
function
__construct(){}}class
ntssi_transgroup
extends
TblObj{public$eg=0;public$Xq=0;public$l="";public$hg="";public$Yj=0;public$gm=0;public$c="group_id";public$b=array("group_id","trans_id","money","permoney");public
function
__construct(){}}class
ntssi_transportation
extends
TblObj{public$cr=0;public$dr="";public$er=0.0;public$br="";public$T="";public$c="transport_id";public$b=array("transport_id","transport_name","transport_price","transport_content","type");public
function
__construct(){}}class
ntssi_transportation_special
extends
TblObj{public$kr=0;public$ik="";public$T=0;public$l="";public$qh="";public$c="trid";public$b=array("trid","name","type","content");public
function
__construct(){}}class
ntssi_transtime
extends
TblObj{public$gr=0;public$hr="";public$c="transtime_id";public$b=array("transtime_id","transtime_name");public
function
__construct(){}}class
ntssi_use_ticket
extends
TblObj{public$Cr=0;public$Bq=0;public$Pr=0;public$Yj=0.0;public$yl="";public$Vr="";public$Zj=0;public$Aq="";public$c="useid";public$b=array("useid","ticketid","userid","money","ordercode","usetime","moneytype");public
function
__construct(){}}class
ntssi_user
extends
TblObj{public$U=0;public$Rr="";public$Ml="";public$Jr=0;public$lr="";public$rp=0;public$mc="";public$Xc="";public$Ac="";public$Is="";public$Ie="";public$uq="";public$Dl="";public$Ka="";public$ym="";public$_g="";public$hf="";public$fo=NULL;public$go="";public$Aj=0;public$sm=0;public$Rq=0;public$qs=0;public$D=0;public$uf="";public$Gr=0;public$db=0.0;public$wd=0;public$Ic="";public$ba="";public$Xo="";public$Rc="";public$Ro=0;public$Gi=0;public$Rh=0;public$Qh=0;public$_e=0;public$Cj="";public$ao="";public$wk="";public$lm="";public$ff="";public$Ds="";public$hk="";public$fc="";public$Yi=0;public$Mb="";public$c="user_id";public$b=array("user_id","username","password","user_state","true_name","sex","born_date","city","canton","zip","email","tel","other_tel","addr","post","idcard","fax","reg_date","reg_ip","member_point","points","toppoints","vloid","provider_id","forum_attr","user_level","advance","companyid","schoolname","chenghu","salepoint","levelpoint","isold","islogin","dianzibao","memberno","recommendno","nickname","pic","facebook_id","yahoo_gid","msn","blog","logincount","authnum");public
function
__construct(){$this->reg_date=new
DateTime();}}class
ntssi_user_level
extends
TblObj{public$Ci=0;public$Di="";public$Ei=0;public$an=0.0;public$c="level_id";public$b=array("level_id","level_name","level_num","pricerate");public
function
__construct(){}}class
ntssi_userticket
extends
TblObj{public$t=0;public$Bq=0;public$Pr=0;public$Jd=0;public$bo=0;public$zi="";public$c="id";public$b=array("id","ticketid","userid","count","recordid","lasttime");public
function
__construct(){}}class
ntssi_visit_ip
extends
TblObj{public$ns=0;public$ms="";public$ks="";public$Bl="";public$Ag="";public$ep=0;public$co="";public$U=0;public$os="";public$ls=NULL;public$c="visit_ip_id";public$b=array("visit_ip_id","visit_ip","visit_agent","os","ie","screen","referrer","user_id","visit_unixtime","visit_idate");public
function
__construct(){$this->visit_idate=new
DateTime();}}class
ntssi_vright
extends
TblObj{public$t=0;public$Xg=0;public$c="id";public$b=array("id","ifopen");public
function
__construct(){}}class
ntssi_waitbuy
extends
TblObj{public$t=0;public$U=0;public$r=0;public$fh=0;public$E="";public$c="id";public$b=array("id","user_id","gid","ifsend","pubtime");public
function
__construct(){}}require_once(MROOT."/../browscap/php-local-browscap.php");function
make_sure_data_schema(){$O="giyn_browser_info";$P=list_tables();$j=list_columns($O);if(in_array($O,$P)&&in_array("cssversion",$j))return;setup_schema($O,"user_id","int(10)      NOT NULL","-1","使用者ID");setup_schema($O,"user_agent","varchar(255) NOT NULL","''","瀏覽器型號描述");setup_schema($O,"chksum","varchar(255) NOT NULL","''","瀏覽器型號描述檢查碼");setup_schema($O,"time","int(10)      NOT NULL","-1","紀錄時間");setup_schema($O,"platform","varchar(255) NOT NULL","''","瀏覽器平台");setup_schema($O,"browser","varchar(255) NOT NULL","''","瀏覽器簡稱");setup_schema($O,"version","varchar(255) NOT NULL","''","瀏覽器版本");setup_schema($O,"comment","varchar(255) NOT NULL","''","瀏覽器全名");setup_schema($O,"parent","varchar(255) NOT NULL","''","瀏覽器繼承型別");setup_schema($O,"cssversion","varchar(255) NOT NULL","''","瀏覽器支援CSS版本");}function
make_sure_browsecap_ini_file(){$ea="http://tempdownloads.browserscap.com/stream.asp?PHP_BrowsCapINI";$da=MROOT."/../browscap/php_browscap.ini";if(file_exists(dirname($da)."/php_browscap.ini"))return;$m=file_get_contents($ea);file_put_contents($da,$m);}function
probe_browser($Fr){require_once(MROOT.'/../browscap/php-local-browscap.php');$e=get_browser_local($Fr,false,MROOT."/../browscap/php_browscap.ini");$y=array("platform","parent","comment","browser","cssversion","version");$H=array();foreach($y
as$w)$H[$w]=$e->$w;$e->browser;$e->comment;$e->cookies;$e->crawler;$e->cssversion;$e->frames;$e->iframes;$e->ismobiledevice;$e->javascript;$e->majorver;$e->minorver;$e->parent;$e->platform;$e->platform_version;$e->tables;$e->version;return$H;}function
search_or_record($U,$Fr){make_sure_data_schema();$Uc=md5($Fr);$Eq=time();$F="SELECT COUNT(*) "." FROM giyn_browser_info "." WHERE user_id=$U "." AND chksum='$Uc' "."";$o=matDB::getDB();$dd=$o->getOne($F);if($dd>0)return;$F="INSERT INTO giyn_browser_info "." ( `user_id`, `user_agent`, `chksum`, `time` ) "." VALUES "." ( $U, '$Fr', '$Uc', $Eq ) "."";$o->query($F);}function
scan_and_save_browser(){if(isset($_SERVER['HTTP_USER_AGENT'])){$Fr=$_SERVER['HTTP_USER_AGENT'];$Uc=md5($Fr);if(isset($_SESSION['user_id']))$U=$_SESSION['user_id'];if($U>0)search_or_record($U,$Fr);}}class
Order{private$Ef=null;private$Cm=null;private$ob=null;static
public
function
listOrders($zd){$Cl=new
ntssi_order_table();$_l=$Cl->select($zd);return$_l;}static
public
function
get($C){$Cl=new
ntssi_order_table();$_l=$Cl->select(array("order_id"=>$C));$Sk=new
ntssi_order_detail();$pl=$Sk->select(array("order_id"=>$C));$H=$_l[0];$H->_detail=$pl;return$H;}}function
create_table_for_godds_sync($n){$J=0;$K=NULL;$o=Database::getInstance();$I=$o->use_database($n);if($I==0){$F=<<<EOD
CREATE TABLE IF NOT EXISTS `ntssi_goods_sync` (
  `site` varchar(100) NOT NULL,
  `key` varchar(100) NOT NULL,
  `gid` int(11) NOT NULL,
  `chksum` varchar(100) NOT NULL,
  `last_chk` varchar(100) NOT NULL,
  `last_changed` varchar(100) NOT NULL,
  KEY (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
EOD;
$I=$o->query_nodata($F);if($I!==0)echo"建立資料庫失敗\n";}else{echo"切換資料庫的步驟有問題\n";$J=-1;}return$J;}function
show_order_states(){$tq=new
ntssi_order_state();$Sh=$tq->select();print_r($Sh);foreach($Sh
as$v){switch($v->state_type){case"1":$Qp="訂單狀態";$x="order_state";break;case"2":$Qp="付款狀態";$x="pay_state";break;case"3":$Qp="出貨狀態";$x="transport_state";break;default:}$Op=str_pad($v->order_state_name,10," ",STR_PAD_RIGHT);$Z=$v->state_value;echo"$Qp: $Op \t [ $x=$Z ]\n";}}function
initTZ(){date_default_timezone_set("Asia/Taipei");}function
initDB(){$k=Conf::getInstance();$Yd=strval($k->get('mysql.host'));$be=strval($k->get('mysql.port'));$ce=strval($k->get('mysql.username'));$ae=strval($k->get('mysql.password'));if($Yd.$be===""&&$ce===""&&$ae===""){$d=explode(":",$k->get('DEFAULT.DBhostname'));if(count($d)==2){$Yd=$d[0];$be=$d[1];}else{$Yd=$d[0];$be="3306";}$ce=$k->get('DEFAULT.DBuserName');$ae=$k->get('DEFAULT.DBpassword');$Zd=$k->get('DEFAULT.DBname');}$o=Database::getInstance();$o->setup($Yd,$be,$ce,$ae);$o->connect();$o->set_database($Zd);}function
path_cmp($ya,$Pb){if($ya==$Pb)return
0;return($ya<$Pb)?-1:1;}function
json_format($Zh){$mq="  ";$B="";$sh=0;$rh=false;$ai=json_decode($Zh);if($ai===false)return
false;$Zh=json_encode($ai);$Ai=strlen($Zh);for($_c=0;$_c<$Ai;$_c++){$f=$Zh[$_c];switch($f){case'{':case'[':if(!$rh){$B.=$f."\n".str_repeat($mq,$sh+1);$sh++;}else$B.=$f;break;case'}':case']':if(!$rh){$sh--;$B.="\n".str_repeat($mq,$sh).$f;}else$B.=$f;break;case',':if(!$rh)$B.=",\n".str_repeat($mq,$sh);else$B.=$f;break;case':':if(!$rh)$B.=": ";else$B.=$f;break;case'"':if($_c>0&&$Zh[$_c-1]!='\\')$rh=!$rh;default:$B.=$f;break;}}return$B;}function
get_schema_from_files($Wo){global$INFO;$H=array();if(file_exists($Wo)){$Ee=scandir($Wo);for($s=0;$s<count($Ee);$s++){$Be=$Ee[$s];$Rd=path_join($Wo,$Be);if($Be=="."||$Be=="..")continue;if(is_dir($Rd)===FALSE)continue;$qf=scandir($Rd);for($Th=0;$Th<count($qf);$Th++){$mf=$qf[$Th];$ef=path_join($Rd,$mf);if($mf=="."||$mf=="..")continue;if(is_file($ef)===FALSE)continue;$df=file_get_contents($ef);$ai=json_decode($df);$x=path_join(basename($Rd),basename($ef));$Z=json_format(json_encode($ai));$H[$x]=$Z;}}}return$H;}function
get_schema_from_database(){$H=array();$P=array();$j=array();$Cd=matDB::getDB();$G=$Cd->CacheGetAll("SHOW TABLES");if($G===false)die("error");foreach($G
as$Q){$O=$Q[0];$lo=$Cd->CacheGetAll("DESCRIBE $O");foreach($lo
as$L){$nq=$O;$i=array("Type"=>$L["Type"],"Null"=>$L["Null"],"Key"=>$L["Key"],"Default"=>$L["Default"],"Extra"=>$L["Extra"],);$x=path_join($nq,$L['Field']);$Z=json_format(json_encode($i));$H[$x]=$Z;}}return$H;}function
trace_db_schema($ma){if(false){$Sd=get_schema_from_database();foreach($Sd
as$x=>$Z){$ef=path_join($ma,$x);$Rd=dirname($ef);prepare_dir($Rd);if(file_exists($ef)===FALSE){$df=$Z;$I=file_put_contents($ef,$df);if($I===FALSE)die("建立 $Rd 檔案失敗");}}}if(false){echo"processing files ...\n";$Td=get_schema_from_files($ma);echo"processing database ...\n";$Sd=get_schema_from_database();$y=array();echo"stage files ...\n";foreach(array_keys($Td)as$x){if(in_array($x,$y))continue;array_push($y,$x);}echo"stage databases ...\n";foreach(array_keys($Sd)as$x){if(in_array($x,$y))continue;array_push($y,$x);}sort($y);echo"comparing ...\n";foreach($y
as$x){$Lh=isset($Sd[$x]);$Mh=isset($Td[$x]);$Oh=($Sd[$x]===$Td[$x]);if($Lh===true&&$Mh===false)echo"$x :: database >> files \n";if($Lh===false&&$Mh===true)echo"$x :: database << files \n";if($Lh===true&&$Mh===true){if($Oh)continue;echo"$x :: database =\= files \n";$bs=$Sd[$x];$cs=$Td[$x];echo"====\n$bs\n====\n$cs\n====\n";}if($Lh===false&&$Mh===false)echo"$x :: 異常 \n";}}$Cd=matDB::getDB();$G=$Cd->CacheGetOne("SELECT DATABASE()");if($G===false||$G===NULL)die("error");$Od=$G;$G=$Cd->CacheGetAll("SHOW TABLES");if($G===false)die("error");$P=array();foreach($G
as$Q)array_push($P,$Q[0]);$j=array();foreach($P
as$O){$mo=$Cd->CacheGetAll("DESCRIBE $O");foreach($mo
as$G){$nq=str_replace($INFO['DBPrefix'],"ntssi_",$O);$i=array("Type"=>$G["Type"],"Null"=>$G["Null"],"Key"=>$G["Key"],"Default"=>$G["Default"],"Extra"=>$G["Extra"],);array_push($j,$i);}}usort($j,"path_cmp");foreach($j
as$v)echo
implode(",",$v)."\n";}class
Column{var$field=NULL;var$type=NULL;var$null=NULL;var$key=NULL;var$default=NULL;var$extra=NULL;}function
run_test(){$G=$DB->query("DESCRIBE ntssi_user");for(;$L=$DB->fetch_array($G);)print_r($L);$lf=new
Column("ddcscom_nhmakeup","ntssi_user","dianzibao");$lf->exists();$lf->install();$Hr=new
Ntssi_User();}function
check_schema($O,$i){$P=list_tables();if(!in_array($O,$P))return
false;$j=list_columns($O);if(!in_array($i,$j))return
false;return
true;}function
list_tables(){$H=array();$o=matDB::getDB();$uo=$o->GetAll("show tables");foreach($uo
as$L){$to=each($L);array_push($H,$to['value']);}return$H;}function
list_columns($O){$H=array();$o=matDB::getDB();$uo=$o->GetAll("describe $O");foreach((array)$uo
as$L)array_push($H,$L['Field']);return$H;}function
hook_and_meter_call($Rk,$_b,$F,$Bi=0){if(!isset($GLOBALS['req_uuid']))$GLOBALS['req_uuid']=substr(uniqid(md5(rand()),true),0,7);$yj=memory_get_usage();$dk=microtime(true);$H=call_user_func_array($Rk,$_b);$fk=microtime(true);$_j=memory_get_usage();{$de=debug_backtrace();do{$nf=basename($de[$Bi]['file']);$Ii=$de[$Bi]['line'];$bd=$de[$Bi]['class']."::".$de[$Bi]['function']."()";$Bi+=1;}while($nf=="mysql.php"||$nf=="mat.php");$zj=$_j-$yj;$ek=$fk-$dk;$ee=sprintf("%s (%9.3f Kb, %6.3f ms )[%s:%s %s] Query: %s ",$GLOBALS['req_uuid'],$zj/1000,$ek,$nf,$Ii,$bd,$F);$jf=fopen('/tmp/debug.log','a+');fwrite($jf,$ee."\n");fclose($jf);}return$H;}function
mysql_debug_query(){$_b=func_get_args();$Ln=str_replace("\r\n"," ",trim($_b[0]));$H=hook_and_meter_call('mysql_query',$_b,$Ln);return$H;}if(class_exists("DB_MySQL")){class
DB_debug_MySQL
extends
DB_MySQL{var$is_debug_class=true;var$old_DB_obj=NULL;function
__construct($Qk){if(isset($Qk->is_debug_class))return$Qk;$this->conn=$Qk->conn;$this->technicalemail=$Qk->technicalemail;$this->utf_String=$Qk->utf_String;$this->old_DB_obj=$Qk;}function
query($Ln){$H=hook_and_meter_call(array($this,'parent::query'),array($Ln),$Ln);return$H;}}function
db_debug_beg(){global$DB;if(!isset($DB->is_debug_class))$DB=new
DB_debug_MySQL($DB);}function
db_debug_end(){global$DB;if(isset($DB->is_debug_class))$DB=$DB->old_DB_obj;}}function
prepare_dir($Ce){if(file_exists($Ce)===FALSE){$al=umask(0);$I=mkdir($Ce,0777,true);umask($al);if($I===FALSE)die("建立 $Ce 目錄失敗");}}class
FTPAgent{public$Dd=NULL;public$tg="";public$Er="";public$Ll="";public
function
enter(){$J=0;$this->conn_id=@ftp_connect($this->host,21,15);if($this->conn_id===FALSE){$J=-1;return$J;}$I=@ftp_login($this->conn_id,$this->user,$this->pass);if($I===FALSE){$J=-2;return$J;}return$J;}public
function
leave(){$J=0;ftp_close($this->conn_id);return$J;}public
function
upload($Ti,$jo){$J=0;$I=ftp_put($this->conn_id,$jo,$Ti,FTP_BINARY);if($I)echo"上傳檔案成功: $Ti -> $jo \n";else
echo"上傳檔案失敗: $Ti -> $jo \n";return$J;}public
function
download($jo,$Ti){$J=0;$I=ftp_get($this->conn_id,$Ti,$jo,FTP_BINARY);if($I)$J=0;else$J=-1;return$J;}public
function
move($Zk,$qk){$J=0;$I=ftp_rename($this->conn_id,$Zk,$qk);if($I)echo"Successfully move file from $Zk to $qk \n";else
echo"There was a problem\n";return$J;}public
function
list_files($ko){$K=array();$G=ftp_nlist($this->conn_id,$ko);if($G!=FALSE){foreach($G
as$L){$of=$L;array_push($K,$of);}}return$K;}}class
FileAgent{static
function
list_files($Ui){$H=array();$G=scandir($Ui);if($G!=FALSE&&is_array($G)){foreach($G
as$L){$of=path_join($Ui,$L);if(is_file($of))array_push($H,$of);}}return$H;}static
function
move($Pl,$Ol){$I=rename($Pl,$Ol);return$I;}}function
get_info_conf_from_file($es){$H="";$Bd=matConf::getConf('info.conf_global_path');$l=file_get_contents($Bd);preg_match("/.*INFO.*".$es.".*=\s*(.*)\s*;/",$l,$wj);if(count($wj)==2){$vj=$wj[1];$vj=str_replace("\"","",$vj);$vj=str_replace("'","",$vj);$H=trim($vj);}return$H;}class
matConf{var$_data=NULL;protected
function
__construct(){if(file_exists(MROOT."/../../configs.inc.php")){global$INFO,$FUNCTIONS;if(isset($INFO)){foreach($INFO
as$x=>$X){$I=preg_match('~\.~',$x);if($I>0||$x=="mod")$this->_data[$x]=$X;else$this->_data["info.".$x]=$X;}if(isset($FUNCTIONS)){$this->_data["info.DBname"]=$FUNCTIONS->authcode($INFO['DBname'],"DECODE",$INFO['site_userc']);$this->_data["info.DBuserName"]=$FUNCTIONS->authcode($INFO['DBuserName'],"DECODE",$INFO['site_userc']);$this->_data["info.DBpassword"]=$FUNCTIONS->authcode($INFO['DBpassword'],"DECODE",$INFO['site_userc']);}}if(file_exists(MROOT."/../../Config/conf.global.php"))$this->_data["info.conf_global_path"]=MROOT."/../../Config/conf.global.php";}else
if(file_exists(MROOT."/../../includes/init.php"));else;}static
public
function
getConf($x){$H=NULL;$k=self::getInstance();if(isset($k->_data[$x]))$H=$k->_data[$x];return$H;}static
public
function
setConf($x,$X){$k=self::getInstance();$k->_data[$x]=$X;}static
private$a=null;static
public
function
getInstance(){if(!self::$a)self::$a=new
self;return
self::$a;}}function
initADODB(){$na=substr(PHP_OS,0,3)=='WIN'?";":":";ini_set("include_path",ini_get("include_path").$na.MROOT."/../adodb");require_once("adodb.inc.php");require_once("tohtml.inc.php");if(file_exists(MROOT."/../../configs.inc.php")){global$INFO,$FUNCTIONS;$aa=MROOT."/../../UploadFile/ADODB_cache";$ma=MROOT."/../../UploadFile/schema";$fe=$INFO['DBhostname'];$ge=$FUNCTIONS->authcode($INFO['DBname'],"DECODE",$INFO['site_userc']);$ie=$FUNCTIONS->authcode($INFO['DBuserName'],"DECODE",$INFO['site_userc']);$he=$FUNCTIONS->authcode($INFO['DBpassword'],"DECODE",$INFO['site_userc']);}else
if(file_exists(MROOT."/../../includes/init.php")){$aa=MROOT."/../../temp/ADODB_cache";$ma=MROOT."/../../temp/schema";$fe=$GLOBALS['db']->settings['dbhost'];$ge=$GLOBALS['db']->settings['dbname'];$ie=$GLOBALS['db']->settings['dbuser'];$he=$GLOBALS['db']->settings['dbpw'];}else;prepare_dir($aa);prepare_dir($ma);$GLOBALS['ADODB_CACHE_DIR']=$aa;$H=array("dbhost"=>$fe,"dbname"=>$ge,"dbuser"=>$ie,"dbpass"=>$he,);return$H;}class
matDB{var$conn=NULL;protected
function
__construct(){$m=initADODB();$fe=$m['dbhost'];$ge=$m['dbname'];$ie=$m['dbuser'];$he=$m['dbpass'];$this->conn=ADONewConnection("mysqli");$this->conn->PConnect($fe,$ie,$he,$ge);$this->conn->SetFetchMode(ADODB_FETCH_ASSOC);$this->conn->Execute("SET NAMES 'utf8' ");}static
private$a=null;static
public
function
getDB(){if(!self::$a)self::$a=new
self;return
self::$a->conn;}}function
get_user_by_id($U){global$INFO;$o=matDB::getDB();$L=$o->GetRow("SELECT * FROM ".$INFO['DBPrefix']."user WHERE user_id=$U LIMIT 1 ");return$L;}function
setup_schema($O,$i,$qr,$ke,$td){$o=matDB::getDB();if(!empty($ke))$ke=" DEFAULT $ke ";{$P=list_tables();if(!in_array($O,$P)){$F="CREATE TABLE `$O` ( "." `$i` "." $qr "." $ke "." COMMENT '$td'"." ) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ; ";$o->Execute($F);}}$j=list_columns($O);if(in_array($i,$j))return;$F="ALTER TABLE `$O` "." ADD `$i` "." $qr "." $ke "." COMMENT '$td'";$o->Execute($F);}function
get_table_collation($Q){$H=NULL;$o=matDB::getDB();$uo=$o->GetAll("SHOW TABLE STATUS");foreach($uo
as$L){if($L['Name']==$Q)$H=$L['Collation'];}return$H;}function
check_table_encoding($O,$hd){$Nd=get_table_collation($O);if($hd==$Nd)return
true;else
return
false;}function
repair_table_encoding($O,$Nc,$hd){$o=matDB::getDB();$F=sprintf("ALTER TABLE `%s` CONVERT TO CHARACTER SET %s COLLATE %s",$O,$Nc,$hd);$o->Execute($F);}function
print_table($d,$q=NULL,$Gd=false){$y=array_keys($d);if($q!=NULL)$y=$q;echo"<table border=1 >","<tr>";foreach((array)$y
as$x)echo
sprintf("<th>%s</th>",$x);echo"</tr>","<tr>";foreach((array)$y
as$x){$Y=$d[$x];if($Gd&&like_timestamp($Y)){$lq=convert_timestamp($Y);$Y=sprintf("%s",$lq[0]);}echo
sprintf("<td>%s</td>",$Y."&nbsp;");}echo"</tr>","</table>";}function
print_table_multi($Cb,$q=NULL,$Ae=NULL,$Gd=false){if(count($Cb)<1)return;$Bb=$Cb[0];$y=array_keys($Bb);if($q!=NULL)$y=$q;echo"<table border=1 >","<tr>";foreach((array)$y
as$x){$pi=isset($Ae[$x])?$Ae[$x]:$x;echo
sprintf("<th>%s</th>",$pi);}echo"</tr>";foreach((array)$Cb
as$d){echo"<tr>";foreach((array)$y
as$x){$Y=$d[$x];if($Gd&&like_timestamp($Y)){$lq=convert_timestamp($Y);$Y=sprintf("%s",$lq[0]);}echo
sprintf("<td>%s</td>",$Y."&nbsp;");}echo"</tr>";}echo"</table>";}function
print_table_90($d,$q=NULL,$Ae=NULL,$Gd=false){$y=array_keys($d);if($q!=NULL)$y=$q;echo"<table border=1 >";foreach((array)$y
as$x){$pi=isset($Ae[$x])?$Ae[$x]:$x;$Y=$d[$x];if($Gd&&like_timestamp($Y)){$lq=convert_timestamp($Y);$Y=sprintf("%s",$lq[0]);}echo
sprintf("<tr><th>%s</th><td>%s<td></tr>",$pi,$Y."&nbsp;");}echo"</table>";}function
is_timestamp($R){$ha=2147483647;$ia=0;$Sc=(strval($R)===strval(intval($R)));$Tc=($ia<=intval($R)&&intval($R)<=$ha);if($Sc&&$Tc)return
true;else
return
false;}function
like_timestamp($R,$Dp="2001-09-11"){$Sc=is_timestamp($R);$Tc=(intval($R)>=strtotime($Dp));if($Sc&&$Tc)return
true;else
return
false;}function
convert_timestamp($R,$sf=NULL){$H=NULL;if(is_timestamp($R)){$H=array();$Fq=intval($R);$H[0]=date("c",$Fq);$H[1]=strftime("%F %T",$Fq);}return$H;}function
get_version($ik){$H=NULL;$Sh=get_defined_constants();foreach($Sh
as$w=>$W){$I=preg_match("/^version\.".$ik."$/",$w);if($I>0){$Zr=explode(".",$W);$H=array();foreach($Zr
as$X){if(!empty($X))array_push($H,$X);}if(count($H)==3){$H['major']=$H[0];$H['minor']=$H[1];$H['patch']=$H[2];}$H['full']=$W;}}return$H;}function
chk_admin(){if(defined("ISSMSP")){$g[2]=isset($_SESSION['LOGINADMIN_session_id'])&&($_SESSION['LOGINADMIN_session_id']=='');$g[3]=(empty($_SESSION['LOGINADMIN_session_id']));$g[4]=($_SESSION['HTTP_USER_AGENT']!=md5($_SERVER['HTTP_USER_AGENT']));$g[0]=!($g[2]||$g[3]||$g[4]);return$g[0];}else
if(defined("ISECSP")){$g[1]=!isset($_SESSION['admin_id']);$g[2]=isset($_SESSION['admin_id'])&&(intval($_SESSION['admin_id'])<=0);$g[0]=!($g[1]||$g[2]);return$g[0];}else
return
false;}?>
