<?php
//nuevoMailer v.3.70
//Copyright 2014 Panagiotis Chourmouziadis
//http://www.nuevomailer.com


/* 
	This file is used in all subscriber pages in the folder subscriber.
	If using a language other than English, translate this file.
	English lines appear at the bottom */

if (isset( $_SERVER["HTTP_ACCEPT_LANGUAGE"]) )	{
	$subLang=strtolower(substr($_SERVER["HTTP_ACCEPT_LANGUAGE"],0,2));
}
else {
 $subLang='en';	//available translations in this file: el, de, pl, es, fr, pt, en, it, nl
}
 
if ($subLang=='es') { //SPANISH
define("DEMOMODE_1", "Disculpe, esta funcion no esta habilitada en modo DEMO.");
define("SUBACCOUNT_1", "Sus suscripciones a Newsletter");
define("SUBACCOUNT_2", "Actualice su cuenta de suscriptor");
define("SUBACCOUNT_3", "Ingrese su email y password para ver y editar sus suscripciones");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Ingrese");
define("SUBACCOUNT_6", "Estimado(a)");
define("SUBACCOUNT_7", "Estas son las listas disponibles para que Ud. pueda suscribirse:");
define("SUBACCOUNT_8", "Verifique la lista a la cual desea suscribirse, realize los cambios a su informacion personal y oprima en Actualizar.");
define("SUBACCOUNT_9", " Actualizar ");
define("SUBACCOUNT_10", "Recordatorio de Password");
define("SUBACCOUNT_11", "Utilice este formulario para obtener su password. Recibirá un email con su password");
define("SUBACCOUNT_12", "Enviar password");
define("SUBACCOUNT_13", "El email y la password ingresados no existen en nuestra base de datos. Intente con otros.");
define("SUBACCOUNT_14", "Por favor ingrese su email!");
define("SUBACCOUNT_15", "Su perfil fue actualizado");
define("SUBACCOUNT_16", "Su password es: ");
define("SUBACCOUNT_17", "Password");
define("SUBACCOUNT_18", "Por favor ingrese su email valido");
define("SUBACCOUNT_19", "Por favor ingrese su password");
define("SUBACCOUNT_20", "Recordatorio de password de Newsletter de ");
define("SUBACCOUNT_21", "Esta cuenta de correo no existe en nuestro sistema.");
define("SUBACCOUNT_22", "Hemos enviado su password.");
define("SUBACCOUNT_23", "Nombre");
define("SUBACCOUNT_24", "Cerrar");
define("SUBACCOUNT_25", "Apellido");
define("SUBACCOUNT_26", "Política de privacidad");
define("SUBACCOUNT_27", "Se ha perdido la informacion de login.");
define("SUBACCOUNT_28", "No hay listas disponibles.");
define("SUBACCOUNT_29", "Ayudenos a mejorar");
define("SUBACCOUNT_30", "Por favor ingrese una razón para su desuscripción");
define("SUBACCOUNT_31", "Informacion de Opt-out no se encuentra. Email no encontrado o no valido.");
define("SUBACCOUNT_32", "Opt out de lista.");
define("SUBACCOUNT_33", "Opt out global.");
define("SUBACCOUNT_34", "Gracias por calificar nuestro newsletter.");
define("SUBACCOUNT_35", "La informacion se ha perdido o no encontrado.");
define("SUBACCOUNT_36", "El email no se ha encontrado o no es valido.");
define("SUBACCOUNT_37", "Reenvie este newsletter a sus amigos");
define("SUBACCOUNT_38", "Newsletter");
define("SUBACCOUNT_39", "Mi nombre");
define("SUBACCOUNT_40", "Mi email");
define("SUBACCOUNT_41", "Deseo reenviar este newsletter a");
define("SUBACCOUNT_42", "Nombre");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Código de verificación");
define("SUBACCOUNT_45", "Enviar");
define("SUBACCOUNT_46", "Política de privacidad");
define("SUBACCOUNT_47", "El email de su amigo no será guardado en nuestra base de datos. Este solo se utilizará para reenviar puntualmente este newsletter.");
define("SUBACCOUNT_48", "reenviado por ");
define("SUBACCOUNT_49", "Muchas gracias");
define("SUBACCOUNT_50", "Su newsletter fue reenviado.");
define("SUBACCOUNT_51", "Este suscriptor se dio de baja o opt-out: ");
define("SUBACCOUNT_52", "Nuevo opt-out");
define("SUBACCOUNT_53", "Ud. tiene un nuevo suscriptor: ");
define("SUBACCOUNT_54", "Nuevo suscriptor");
define("SUBACCOUNT_55", "Des-suscribir");
// new lines in v.2.00
define("ARCHIVE_1", "Nuestros newsletters");
define("ARCHIVE_2", "Seleccione un newsletter");
define("ARCHIVE_3", "Archivo de newsletter");
define("SUBACCOUNT_56", "Compańia");
define("SUBACCOUNT_57", "Dirección");
define("SUBACCOUNT_58", "Ciudad");
define("SUBACCOUNT_59", "Código postal");
define("SUBACCOUNT_60", "Estado/Región");
define("SUBACCOUNT_61", "Pais");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Celular ");
define("SUBACCOUNT_65", "Fecha nacimiento");
define("SUBACCOUNT_66", "Seleccione");
// new lines in v.3.50
define("ARCHIVE_4", "No newsletters available");
define("SUBACCOUNT_67", "Missing data");
define("SUBACCOUNT_68", "You must enter your name and email and the verification code that you see.");
define("SUBACCOUNT_69", "Please enter valid emails.");
// new lines in v.3.60
define("SUBACCOUNT_70", "You clicked a correctly formatted opt-out link.<br>However, since this is a test email nothing happens.<br>In order to fully try your opt-out links send a campaign to your own test list.");
define("SUBACCOUNT_71", "You clicked a confirmation link.<br>However since this is a test email nothing will happen.<br>In order to fully test your confirmation link send a campaign to your own test list or subscribe using an opt-in form.");
}
else if ($subLang=='nl') { 
define("DEMOMODE_1", "Sorry, this feature is disabled in demo mode.");
define("SUBACCOUNT_1", "Uw abonnementen op nieuwsbrieven");
define("SUBACCOUNT_2", "Update uw nieuwsbrief rekening");
define("SUBACCOUNT_3", "Vul uw emailadres en wachtwoord in om te zien en je abonnementen beheren");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Enter");
define("SUBACCOUNT_6", "Geachte");
define("SUBACCOUNT_7", "Hier zijn de beschikbare lijsten voor u te abonneren:");
define("SUBACCOUNT_8", "Vink de lijsten die u wilt abonneren, wijzigingen in uw persoonlijke gegevens te maken en klik op Bijwerken.");
define("SUBACCOUNT_9", " Bijwerken ");
define("SUBACCOUNT_10", "Wachtwoord herinnering");
define("SUBACCOUNT_11", "Gebruik dit formulier om uw wachtwoord te verkrijgen. U ontvangt vervolgens uw wachtwoord in uw email");
define("SUBACCOUNT_12", "Stuur wachtwoord");
define("SUBACCOUNT_13", "Het emailadres en wachtwoord dat u hebt ingevoerd niet bestaan in onze database. Probeer het opnieuw.");
define("SUBACCOUNT_14", "Vul uw email!");
define("SUBACCOUNT_15", "Je profiel is gewijzigd");
define("SUBACCOUNT_16", "Uw wachtwoord is: ");
define("SUBACCOUNT_17", "Wachtwoord");
define("SUBACCOUNT_18", "Vul alstublieft een geldig emailadres");
define("SUBACCOUNT_19", "Vul je wachtwoord in");
define("SUBACCOUNT_20", "Nieuwsbrief wachtwoord herinnering uit ");
define("SUBACCOUNT_21", "Dit email account bestaat niet.");
define("SUBACCOUNT_22", "Wij hebben u uw wachtwoord verzonden.");
define("SUBACCOUNT_23", "Naam");
define("SUBACCOUNT_24", "Sluiten");
define("SUBACCOUNT_25", "Achternaam");
define("SUBACCOUNT_26", "Privacy Verklaring");
define("SUBACCOUNT_27", "Inloggen gegevens ontbreken.");
define("SUBACCOUNT_28", "Geen lijsten.");
define("SUBACCOUNT_29", "Help ons te verbeteren");
define("SUBACCOUNT_30", "Geef een reden voor afmelding");
define("SUBACCOUNT_31", "Opt-out informatie ontbreekt. Email ontbreekt of niet geldig.");
define("SUBACCOUNT_32", "List opt out.");
define("SUBACCOUNT_33", "Global opt out.");
define("SUBACCOUNT_34", "Bedankt voor het beoordelen van onze nieuwsbrief.");
define("SUBACCOUNT_35", "Informatie ontbreekt.");
define("SUBACCOUNT_36", "E-mail ontbreekt of niet geldig.");
define("SUBACCOUNT_37", "Stuur deze nieuwsbrief aan uw vrienden");
define("SUBACCOUNT_38", "Nieuwsbrief");
define("SUBACCOUNT_39", "Mijn naam");
define("SUBACCOUNT_40", "Mijn email");
define("SUBACCOUNT_41", "Ik wil deze nieuwsbrief doorsturen naar");
define("SUBACCOUNT_42", "Naam");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Verificatiecode");
define("SUBACCOUNT_45", "Opsturen");
define("SUBACCOUNT_46", "Privacy verklaring");
define("SUBACCOUNT_47", "Emailadressen van uw vrienden worden niet bewaard. Ze zullen alleen gebruikt worden om deze nieuwsbrief doorsturen.");
define("SUBACCOUNT_48", "doorgestuurd door");
define("SUBACCOUNT_49", "Dank u!");
define("SUBACCOUNT_50", "Uw nieuwsbrief is doorgestuurd.");
define("SUBACCOUNT_51", "Deze abonnee uitschrijft: ");
define("SUBACCOUNT_52", "Nieuwe opt-out");
define("SUBACCOUNT_53", "U heeft een nieuwe abonnee: ");
define("SUBACCOUNT_54", "Nieuwe abonnee");
define("SUBACCOUNT_55", "Uitschrijven");
// new lines in v.2.00
define("ARCHIVE_1", "Onze nieuwsbrieven");
define("ARCHIVE_2", "Selecteer een nieuwsbrief");
define("ARCHIVE_3", "Nieuwsbrief archief");
define("SUBACCOUNT_56", "Firma");
define("SUBACCOUNT_57", "Adres");
define("SUBACCOUNT_58", "Stad");
define("SUBACCOUNT_59", "Postcode");
define("SUBACCOUNT_60", "Provincie");
define("SUBACCOUNT_61", "Land");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Mobile ");
define("SUBACCOUNT_65", "Verjaardag");
define("SUBACCOUNT_66", "Kiezen");
// new lines in v.3.50
define("ARCHIVE_4", "Geen nieuwsbrieven beschikbaar");
define("SUBACCOUNT_67", "Ontbrekende gegevens");
define("SUBACCOUNT_68", "U moet uw naam en email en de verificatie code die u ziet in te voeren.");
define("SUBACCOUNT_69", "U moet geldig emails in te voeren.");
// new lines in v.3.60
define("SUBACCOUNT_70", "You clicked a correctly formatted opt-out link.<br>However, since this is a test email nothing happens.<br>In order to fully try your opt-out links send a campaign to your own test list.");
define("SUBACCOUNT_71", "You clicked a confirmation link.<br>However since this is a test email nothing will happen.<br>In order to fully test your confirmation link send a campaign to your own test list or subscribe using an opt-in form.");
}	

else if ($subLang=='it') { //ITALIAN
define("DEMOMODE_1", "Ci dispiace ma questa funzione non e abilitata nella demo.");
define("SUBACCOUNT_1", "La tua sottoscrizione alla newsletter");
define("SUBACCOUNT_2", "Aggiorna la tua sottoscrizione");
define("SUBACCOUNT_3", "Inserisci la tua email e password per modificare i tuoi dati");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Inserisci");
define("SUBACCOUNT_6", "Caro");
define("SUBACCOUNT_7", "Qui vi sono le liste per le quali sei iscritto :");
define("SUBACCOUNT_8", "Controlla la lista per quale ti vuoi iscrivere, esegui le modifiche e premi su AGGIORNA.");
define("SUBACCOUNT_9", " Aggiorna ");
define("SUBACCOUNT_10", "Ricorda la password");
define("SUBACCOUNT_11", "Utilizza questo form per avere la tua password. La riceverai tramite email.");
define("SUBACCOUNT_12", "Invia password");
define("SUBACCOUNT_13", "Email e password inserite non esistono. Per favore prova di nuovo.");
define("SUBACCOUNT_14", "Per favore inserisci la tua email!");
define("SUBACCOUNT_15", "Profilo aggiornato");
define("SUBACCOUNT_16", "La tua password: ");
define("SUBACCOUNT_17", "Password");
define("SUBACCOUNT_18", "Per favore inserisci un indirizzo email valido");
define("SUBACCOUNT_19", "Per favore inserisci la password");
define("SUBACCOUNT_20", "Ricorda la Newsletter da ");
define("SUBACCOUNT_21", "Questo account email non esiste.");
define("SUBACCOUNT_22", "Abbiamo definito la tua password.");
define("SUBACCOUNT_23", "Nome");
define("SUBACCOUNT_24", "Chiudi");
define("SUBACCOUNT_25", "Cognome");
define("SUBACCOUNT_26", "Privacy Policy");
define("SUBACCOUNT_27", "Informazioni di Login Mancanti.");
define("SUBACCOUNT_28", "Nessuna lista disponibile.");
define("SUBACCOUNT_29", "Desideriamo Migliorare");
define("SUBACCOUNT_30", "Per favore, potresti scrivere le ragioni della tua cancellazione qui (opzionale)");
define("SUBACCOUNT_31", "Opt-out informazioni mancanti. Email mancante o non valida.");
define("SUBACCOUNT_32", "Lista opt out.");
define("SUBACCOUNT_33", "Opt out globale.");
define("SUBACCOUNT_34", "Grazie per aver espresso il tuo parere sulla newsletter.");
define("SUBACCOUNT_35", "Informazione mancante.");
define("SUBACCOUNT_36", "Email mancante o non valida.");
define("SUBACCOUNT_37", "Invia questa newsletter ad un amico");
define("SUBACCOUNT_38", "Newsletter");
define("SUBACCOUNT_39", "Mio Nome");
define("SUBACCOUNT_40", "Mia email");
define("SUBACCOUNT_41", "Desidero inviare questa newsletter a");
define("SUBACCOUNT_42", "Nome");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Codice di Verifica");
define("SUBACCOUNT_45", "Invia");
define("SUBACCOUNT_46", "Notizie sulla Privacy");
define("SUBACCOUNT_47", "Gli indirizzi email dei tuoi amici non verranno inseriti automaticamente nella newsletter ma solo per conoscenza tramite il tuo inoltro.");
define("SUBACCOUNT_48", "inoltrata da ");
define("SUBACCOUNT_49", "Grazie");
define("SUBACCOUNT_50", "Newsletter inoltrata correttamente.");
define("SUBACCOUNT_51", "Iscritto uscito opted-out: ");
define("SUBACCOUNT_52", "Nuova cancellazione");
define("SUBACCOUNT_53", "Hai un nuovo iscritto: ");
define("SUBACCOUNT_54", "Nuovo iscritto");
define("SUBACCOUNT_55", "Cancellati");
// new lines in v.2.00
define("ARCHIVE_1", "Le nostre newsletter");
define("ARCHIVE_2", "Seleziona una newsletter");
define("ARCHIVE_3", "Newsletter archivio");
define("SUBACCOUNT_56", "Azienda");
define("SUBACCOUNT_57", "Indirizzo");
define("SUBACCOUNT_58", "Citta");
define("SUBACCOUNT_59", "Cap");
define("SUBACCOUNT_60", "Provincia");
define("SUBACCOUNT_61", "Nazione");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Cell ");
define("SUBACCOUNT_65", "Compleanno");
define("SUBACCOUNT_66", "Seleziona");
// new lines in v.3.50
define("ARCHIVE_4", "Nessuna newsletter disponibile");
define("SUBACCOUNT_67", "Manca la data");
define("SUBACCOUNT_68", "Devi inserire nome, cognome e codice di verifica.");
define("SUBACCOUNT_69", "Per favore inserisci email valide.");
// new lines in v.3.60
define("SUBACCOUNT_70", "Hai fatto click sul link di cancellazione opt-out.<br>Tuttavia, se attiva la modalita test questa operazione non funziona.<br>Per provare realmente la tua cancellazione opt-out con link, invia una newsletter ad una campagna della tua lista.");
define("SUBACCOUNT_71", "Hai fatto click su un link di conferma.<br>Tuttavia, se attiva la modalita test questa operazione non funziona.<br>>Per provare realmente la tua cancellazione opt-out con link, invia una newsletter ad una campagna della tua lista o sottoscriun modulo opt-in.");
}
else if ($subLang=='fr') { //FRENCH
define("DEMOMODE_1", "Désolé, cette fonctionnalité est désactivée en mode démo.");
define("SUBACCOUNT_1", "Votre inscription à la Newsletter");
define("SUBACCOUNT_2", "Mettez à jour votre compte");
define("SUBACCOUNT_3", "Entrez votre email et mot de passe pour voir et gérer vos inscriptions");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Entrez");
define("SUBACCOUNT_6", "Chère/Cher");
define("SUBACCOUNT_7", "Ici sont disponibles les listes auxquelles vous pouvez vous inscrire :");
define("SUBACCOUNT_8", "Regardez les listes pour lesquelles vous voulez vous inscrire, faites les changements dans vos données personnelles et cliquez sur Mise à Jour.");
define("SUBACCOUNT_9", " Mise à jour ");
define("SUBACCOUNT_10", "Rappel du Mot de Passe");
define("SUBACCOUNT_11", "Utilisez cette page pour obtenir votre mot de passe. Vous recevrez votre mot de passe dans votre email");
define("SUBACCOUNT_12", "Envoyer le Mot de Passe");
define("SUBACCOUNT_13", "L'email et le mot de passe que vous avez entrés n'existent pas dans notre base de données. Réessayez s'il vous plaît.");
define("SUBACCOUNT_14", "Entrez votre email s'il vous plaît !");
define("SUBACCOUNT_15", "Votre profil a été mise à jour");
define("SUBACCOUNT_16", "Votre Mot de Passe est : ");
define("SUBACCOUNT_17", "Mot de Passe");
define("SUBACCOUNT_18", "Entrez une adresse email valide s'il vous plaît");
define("SUBACCOUNT_19", "Entrez votre Mot de Passe s'il vous plaît");
define("SUBACCOUNT_20", "Rappel de mot de passe de Newsletter de ");
define("SUBACCOUNT_21", "L'email n'est pas associé à un compte.");
define("SUBACCOUNT_22", "Nous vous avons envoyé votre Mot de Passe.");
define("SUBACCOUNT_23", "Prénom");
define("SUBACCOUNT_24", "Fermer");
define("SUBACCOUNT_25", "Nom");
define("SUBACCOUNT_26", "Déclaration de Confidentialité");
define("SUBACCOUNT_27", "Vos identifiants sont incorrects.");
define("SUBACCOUNT_28", "Pas de liste disponible.");
define("SUBACCOUNT_29", "Aidez-nous à améliorer");
define("SUBACCOUNT_30", "Merci de nous donner la raison de votre désinscription");
define("SUBACCOUNT_31", "L'information de désinscription est manquante. Email manquant ou non valide.");
define("SUBACCOUNT_32", "Désinscription de la liste.");
define("SUBACCOUNT_33", "Désinscription de toutes les listes et du site");
define("SUBACCOUNT_34", "Merci d'avoir évalué notre newsletter.");
define("SUBACCOUNT_35", "Information manquante.");
define("SUBACCOUNT_36", "Email manquant ou non valide.");
define("SUBACCOUNT_37", "Tranférez cette newsletter à un ami");
define("SUBACCOUNT_38", "Newsletter");
define("SUBACCOUNT_39", "Mon nom");
define("SUBACCOUNT_40", "Mon email");
define("SUBACCOUNT_41", "Je souhaite transférer cette newsletter à");
define("SUBACCOUNT_42", "Nom");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Code de vérification");
define("SUBACCOUNT_45", "Envoyez la");
define("SUBACCOUNT_46", "Mentions Légales");
define("SUBACCOUNT_47", "Les adresses email de vos amis ne sont pas sauvegardées. Elles seront seulement utilisées pour transférer cette newsletter.");
define("SUBACCOUNT_48", "transféré par ");
define("SUBACCOUNT_49", "Merci");
define("SUBACCOUNT_50", "Votre newsletter a été tranferée.");
define("SUBACCOUNT_51", "Cet utilisateur s'est désinscrit : ");
define("SUBACCOUNT_52", "Nouveau désinscrit");
define("SUBACCOUNT_53", "Vous avez un nouvel inscrit : ");
define("SUBACCOUNT_54", "Nouvel inscrit");
define("SUBACCOUNT_55", "Désinscrit");
// new lines in v.2.00
define("ARCHIVE_1", "Nos newsletters");
define("ARCHIVE_2", "Sélectionnez une newsletter");
define("ARCHIVE_3", "Newsletter archivée");
define("SUBACCOUNT_56", "Société");
define("SUBACCOUNT_57", "Adresse");
define("SUBACCOUNT_58", "Ville");
define("SUBACCOUNT_59", "Code Postal");
define("SUBACCOUNT_60", "Région");
define("SUBACCOUNT_61", "Pays");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Tel mobile ");
define("SUBACCOUNT_65", "Anniversaire");
define("SUBACCOUNT_66", "Selectionnez");
// new lines in v.3.50
define("ARCHIVE_4", "Pas de newsletters disponible");
define("SUBACCOUNT_67", "Données manquantes");
define("SUBACCOUNT_68", "Vous devez entrer votre nom, votre email et le code de vérification que vous voyez.");
define("SUBACCOUNT_69", "Merci d'entrer un email valide.");
// new lines in v.3.60
define("SUBACCOUNT_70", "Vous venez de cliquer sur un lien d'Opt-out correctement formatté.<br/>Cependant, comme ceci était un test, vous n'avez pas été désinscrit de la base des abonnés.<br/>Si vous souhaitez tester l'Opt-out, envoyez une campagne à votre liste de test.");
define("SUBACCOUNT_71", "Vous venez de cliquer sur un lien de confirmation.<br/>Cependant, comme ceci était un test, votre compte n'a pas été confirmé.<br/>Si vous souhaitez tester la confirmation de compte, envoyez une campagne à votre liste de test.");
}
else if ($subLang=='pl') { //POLISH
define("DEMOMODE_1", "Przykro nam ale ta czynność nie jest dostępna w trybie DEMO / Sorry, this feature is disabled in demo mode.");
define("SUBACCOUNT_1", "Twoje subskrypcje Newsletter / Your Newsletter subscriptions");
define("SUBACCOUNT_2", "Zaktualizuj Twoje konto abonenta / Update your subscriber account");
define("SUBACCOUNT_3", "Wpisz swój e-mail i hasło, aby zobaczyć i zarządzać subskrypcjami Newsletter / Enter your email and password to see and manage your subscriptions");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Enter");
define("SUBACCOUNT_6", "Drogi/a / Dear");
define("SUBACCOUNT_7", "Oto dostępne Newsletters, do których można subskrybować / Here are the available lists for you to subscribe:");
define("SUBACCOUNT_8", "Sprawdź listy, które chcesz zapisać, wprowadzić zmiany do swoich danych osobowych i kliknij Update. / Check the lists that you want to subscribe, make changes to your personal data and click on Update.");
define("SUBACCOUNT_9", " Update ");
define("SUBACCOUNT_10", "Przypomnienie hasła / Password reminder");
define("SUBACCOUNT_11", "Użyj tego formularza, aby uzyskać hasło. Otrzymasz hasło w wiadomości e-mail / Use this form to obtain your password. You will receive your password in your email");
define("SUBACCOUNT_12", "Wyślioj hasło / Send password");
define("SUBACCOUNT_13", "E-mail i hasło nie istnieje w naszej bazie. Prosimy spróbować ponownie. / The email and password you entered do not exist in our database. Please try again.");
define("SUBACCOUNT_14", "Wpisz swój adres email! / Please enter your email!");
define("SUBACCOUNT_15", "Twój profil został zaktualizowany / Your profile was updated");
define("SUBACCOUNT_16", "Twoje hasło jest: / Your password is: ");
define("SUBACCOUNT_17", "Hasło / Password");
define("SUBACCOUNT_18", "Wpisz swój poprawny adres email / Please enter your valid email address");
define("SUBACCOUNT_19", "Wpisz swoje hasło / Please enter your password");
define("SUBACCOUNT_20", "Przypomnienie hasła Newsletter od / Newsletter password reminder from ");
define("SUBACCOUNT_21", "Ten e-mail adres nie istnieje. / This email account does not exist.");
define("SUBACCOUNT_22", "Wysłaliśmy Ci Twoje hasło. / We have sent you your password.");
define("SUBACCOUNT_23", "Imię / Name");
define("SUBACCOUNT_24", "Zamknij / Close");
define("SUBACCOUNT_25", "Nazwisko / Last name");
define("SUBACCOUNT_26", "Ochrona prywatności / Privacy statement");
define("SUBACCOUNT_27", "Brakuje informacji logowania / Login information is missing.");
define("SUBACCOUNT_28", "Nie ma dostępnych list / No available lists.");
define("SUBACCOUNT_29", "Pomóż nam ulepszyć / Help us improve");
define("SUBACCOUNT_30", "Proszę podać powód do wypisywania / Please enter a reason for unsubscribing");
define("SUBACCOUNT_31", "Brakuje informacji. Brak email lub nieprawidłowy. / Opt-out information is missing. Email missing or not valid.");
define("SUBACCOUNT_32", "Lista zrezygnowań / List opt out.");
define("SUBACCOUNT_33", "Całkowite wypisanie / Global opt out.");
define("SUBACCOUNT_34", "Dziękujemy za Ocenę naszego newsletter / Thank you for rating our newsletter.");
define("SUBACCOUNT_35", "Brak informacji / Information is missing.");
define("SUBACCOUNT_36", "Brak email lub nie prawidłowy / Email is missing or not valid.");
define("SUBACCOUNT_37", "Prześlij ten newsletter do znajomych / Forward this newsletter to your friends");
define("SUBACCOUNT_38", "Nazwa newsletter / Newsletter title");
define("SUBACCOUNT_39", "Moje imię / My name");
define("SUBACCOUNT_40", "Mój email / My email");
define("SUBACCOUNT_41", "Chcę przesłać ten newsletter do / I want to forward this newsletter to");
define("SUBACCOUNT_42", "Imie / Name");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Kod weryfikacyjny / Verification code");
define("SUBACCOUNT_45", "Wyślij / Send it");
define("SUBACCOUNT_46", "Informacja o prywatności / Privacy notice");
define("SUBACCOUNT_47", "Adresy twoich przyjaciół nie są zachowywane. Będą one użyte jedynie w celu przekazania niniejszego newsletter. / Your friends' email addresses are not kept. They will only be used to forward this newsletter.");
define("SUBACCOUNT_48", "Przekazane przez / forwarded by ");
define("SUBACCOUNT_49", "Dziękujemy / Thank you");
define("SUBACCOUNT_50", "Newsletter został przesłany / Your newsletter was forwarded.");
define("SUBACCOUNT_51", "Ten subskrybent wypisał się / This subscriber opted-out: ");
define("SUBACCOUNT_52", "Nowy wypis / New opt-out");
define("SUBACCOUNT_53", "Jest nowy subskrybent / You have a new subscriber: ");
define("SUBACCOUNT_54", "Nowy subskrybent / New subscriber");
define("SUBACCOUNT_55", "Wypisz się / Un-subscribe");
// new lines in v.2.00
define("ARCHIVE_1", "Nasze newsletter / Our newsletters");
define("ARCHIVE_2", "Wybierz newsletter / Select a newsletter");
define("ARCHIVE_3", "Archiwum newsletters /Newsletter archive");
define("SUBACCOUNT_56", "Firma / Company");
define("SUBACCOUNT_57", "Adres / Address");
define("SUBACCOUNT_58", "Miasto / City");
define("SUBACCOUNT_59", "Kod pocztowy / Zip");
define("SUBACCOUNT_60", "Stan / State");
define("SUBACCOUNT_61", "Państwo Country");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Komórka / Mobile ");
define("SUBACCOUNT_65", "Urodziny / Birthday");
define("SUBACCOUNT_66", "Wybierz / Select");
// new lines in v.3.50
define("ARCHIVE_4", "'Keine Newsletters vorhanden'");
define("SUBACCOUNT_67", "Missing data");
define("SUBACCOUNT_68", "You must enter your name and email and the verification code that you see.");
define("SUBACCOUNT_69", "Please enter valid emails.");
// new lines in v.3.60
define("SUBACCOUNT_70", "You clicked a correctly formatted opt-out link.<br>However, since this is a test email nothing happens.<br>In order to fully try your opt-out links send a campaign to your own test list.");
define("SUBACCOUNT_71", "You clicked a confirmation link.<br>However since this is a test email nothing will happen.<br>In order to fully test your confirmation link send a campaign to your own test list or subscribe using an opt-in form.");
}
else if ($subLang=='el') { //GREEK
define("DEMOMODE_1", "Η λειτουργια αυτη δεν ειναι διαθεσιμη στο demo.");
define("SUBACCOUNT_1", "Your Newsletter subscriptions");
define("SUBACCOUNT_2", "Ενημέρωση λογαριασμού συνδρομών newsletter");
define("SUBACCOUNT_3", "Για να δειτε και να διαχειριστειτε τις συνδρομες σας δωστε το email σας και τον κωδικό πρόσβασης");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Είσοδος");
define("SUBACCOUNT_6", "Καλωσορίσατε");
define("SUBACCOUNT_7", "Λίστες στις οποίες μπορείτε να εγγραφείτε:");
define("SUBACCOUNT_8", "Επιλέξτε τις λίστες που σας ενδιαφέρουν, συμπληρώστε τα προσωπικά σας στοιχεία και πατήστε Ενημέρωση.");
define("SUBACCOUNT_9", " Ενημέρωση ");
define("SUBACCOUNT_10", "Υπενθυμιση κωδικού πρόσβασης");
define("SUBACCOUNT_11", "Εισάγετε το email σας και θα σας σταλεί ο κωδικός πρόσβασης.");
define("SUBACCOUNT_12", "Αποστολη κωδικού πρόσβασης");
define("SUBACCOUNT_13", "Ο συνδυασμος email και κωδικού πρόσβασης δεν ειναι σωστός. Προσπαθήστε ξανά.");
define("SUBACCOUNT_14", "Παρακαλώ εισάγετε το  email σας!");
define("SUBACCOUNT_15", "Η ενημέρωση του λογαριασμού σας ήταν επιτυχής.");
define("SUBACCOUNT_16", "Ο κωδικός πρόσβασης ειναι: ");
define("SUBACCOUNT_17", "Κωδικός πρόσβασης");
define("SUBACCOUNT_18", "Παρακαλώ εισάγετε ένα έγκυρο email");
define("SUBACCOUNT_19", "Παρακαλώ εισάγετε τον κωδικό πρόσβασης");
define("SUBACCOUNT_20", "Υπενθύμιση κωδικού πρόσβασης στο λοαγαριασμό σας Newsletter από ");
define("SUBACCOUNT_21", "Αυτό το email δεν υπάρχει.");
define("SUBACCOUNT_22", "Σας αποστείλαμε τον κωδικό πρόσβασης.");
define("SUBACCOUNT_23", "Όνομα");
define("SUBACCOUNT_24", "Κλείσιμο");
define("SUBACCOUNT_25", "Επώνυμο");
define("SUBACCOUNT_26", "Πολιτική απορρήτου");
define("SUBACCOUNT_27", "Λείπουν τα στοιχεία εισόδου.");
define("SUBACCOUNT_28", "Δεν υπάρχουν διαθέσιμες λίστες.");
define("SUBACCOUNT_29", "Θέλουμε τη γνωμη σας / Help us improve");
define("SUBACCOUNT_30", "Παρκαλώ πείτε μας το λόγο της διαγραφής σας.");
define("SUBACCOUNT_31", "Λείπουν τα απαραίτητα στοιχεία για τη διαγραφή. Ανύπαρκτο ή άκυρο Email.");
define("SUBACCOUNT_32", "Διαγραφή απο λίστα.");
define("SUBACCOUNT_33", "Οριστική διαγραφή.");
define("SUBACCOUNT_34", "Ευχαριστούμε για την αξιολόγηση του newsletter.");
define("SUBACCOUNT_35", "Λείπουν πληροφορίες.");
define("SUBACCOUNT_36", "Ανύπαρκτο ή άκυρο Email.");
define("SUBACCOUNT_37", "Προωθήστε το newsletter στους φίλους σας");
define("SUBACCOUNT_38", "Newsletter");
define("SUBACCOUNT_39", "Το όνομά μου");
define("SUBACCOUNT_40", "Το email μου");
define("SUBACCOUNT_41", "Θέλω να προωθήσω το newsletter στους");
define("SUBACCOUNT_42", "Όνομα");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Κωδικός επαλήθευσης");
define("SUBACCOUNT_45", "Αποστολή");
define("SUBACCOUNT_46", "Περί προσωπικών δεδομένων");
define("SUBACCOUNT_47", "Τα email των φίλων σας δεν αποθηκεύονται. Θα χρησιμοποιηθούν μόνο για την προώθηση του newsletter.");
define("SUBACCOUNT_48", "διαβιβάστηκε από ");
define("SUBACCOUNT_49", "Ευχαριστούμε");
define("SUBACCOUNT_50", "Το newsletter απεστάλη.");
define("SUBACCOUNT_51", "Αυτός ο συνδρομητής διεγράφη: ");
define("SUBACCOUNT_52", "Νέα διαγραφή");
define("SUBACCOUNT_53", "Έχετε ένα νέο συνδρομητή: ");
define("SUBACCOUNT_54", "Νέος συνδρομητής");
define("SUBACCOUNT_55", "Διαγραφή");
// new lines in v.2.00
define("ARCHIVE_1", "Διαθέσιμα newsletters");
define("ARCHIVE_2", "Επιλέξτε ένα newsletter");
define("ARCHIVE_3", "Αρχείο Newsletters");
define("SUBACCOUNT_56", "Εταιρεία");
define("SUBACCOUNT_57", "Διεύθυνση");
define("SUBACCOUNT_58", "Πόλη");
define("SUBACCOUNT_59", "ΤΚ");
define("SUBACCOUNT_60", "Πολιτεία");
define("SUBACCOUNT_61", "Χώρα");
define("SUBACCOUNT_62", "Τηλ. 1");
define("SUBACCOUNT_63", "Τηλ. 2");
define("SUBACCOUNT_64", "Κινητό");
define("SUBACCOUNT_65", "Γενέθλια");
define("SUBACCOUNT_66", "Επιλέξτε");
// new lines in v.3.50
define("ARCHIVE_4", "Δε βρεθηκαν newsletters.");
define("SUBACCOUNT_67", "Λείπουν στοιχεια.");
define("SUBACCOUNT_68", "Εισάγετε όνομα, email τον κωδικό επαλήθευσης.");
define("SUBACCOUNT_69", "Εισάγετε έγκυρα emails.");
// new lines in v.3.60
define("SUBACCOUNT_70", "Κάνατε κλικ στο συνδεσμο διαγραφής ο οποιος δειχνει να ειναι σωστος.<br>Όμως δε διαγραφεστε γιατι αυτο ήταν ενα δοκιμαστικο email.<br>Για πραγματικη δοκιμη στειλτε μια καμπανια σε μια λιστα δοκιμων.");
define("SUBACCOUNT_71", "Κάνατε κλικ στο συνδεσμο επιβεβαιώσης εγγραφής .<br>Όμως δε συμβαινει τιποτα γιατι αυτο ήταν ενα δοκιμαστικο email.<br>Για πραγματικη δοκιμη στειλτε μια καμπανια σε μια λιστα δοκιμων ή χρησιμοποιήστε μια φόρμα εγγραφής.");
}
else if ($subLang=='de') { //GERMAN
define("DEMOMODE_1", "Entschuldigung, dieses Feature ist in Demo-Modus nicht vorhanden.");
define("SUBACCOUNT_1", "Ihre abonnierten Newsletters");
define("SUBACCOUNT_2", "Updaten Sie Ihr Mitgliederkonto");
define("SUBACCOUNT_3", "Geben Sie Email und Passwort ein, um Ihre abonnierten Newsletters anzuschauen und anzupassen");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Eingeben");
define("SUBACCOUNT_6", "Guten Tag");
define("SUBACCOUNT_7", "Sie können sich zu den folgenden Newslettern einschreiben:");
define("SUBACCOUNT_8", "Setzen Sie Haken, um sich bei den Newsletters einzuschreiben, passen Sie Ihre persönlichen Daten an und klicken Sie auf Anpassen.");
define("SUBACCOUNT_9", " Anpassen ");
define("SUBACCOUNT_10", "Passwort-Erinnerung");
define("SUBACCOUNT_11", "Füllen Sie dieses Formular aus und Ihr Passwort wird Ihnen per Email versandt.");
define("SUBACCOUNT_12", "Passwort versenden");
define("SUBACCOUNT_13", "Email und Passwort existieren nicht. Versuchen Sie es bitte noch einmal.");
define("SUBACCOUNT_14", "Geben Sie bitte Ihre Emailadresse ein!");
define("SUBACCOUNT_15", "Ihre Angaben wurden angepasst");
define("SUBACCOUNT_16", "Ihr Passwort ist: ");
define("SUBACCOUNT_17", "Passwort");
define("SUBACCOUNT_18", "Bitte geben Sie Ihre gültige Emailadresse ein");
define("SUBACCOUNT_19", "Bitte geben sie Ihre Passwort ein");
define("SUBACCOUNT_20", "Newsletter-Passwort-Erinnerung von ");
define("SUBACCOUNT_21", "Dieses Email-Konto existiert nicht.");
define("SUBACCOUNT_22", "Ihr Passwort wurde Ihnen gemailt.");
define("SUBACCOUNT_23", "Vorname");
define("SUBACCOUNT_24", "Schliessen");
define("SUBACCOUNT_25", "Nachname");
define("SUBACCOUNT_26", "Datenschutz");
define("SUBACCOUNT_27", "Login-Angaben fehlen.");
define("SUBACCOUNT_28", "Keine Liste vorhanden.");
define("SUBACCOUNT_29", "Helfen Sie uns, weiter zu kommen");
define("SUBACCOUNT_30", "Geben Sie bitte an, wieso Sie sich abmelden");
define("SUBACCOUNT_31", "Opt-out Information fehlerhaft. Email fehlt oder ist nicht gültig.");
define("SUBACCOUNT_32", "Opt-out von Liste.");
define("SUBACCOUNT_33", "Globale Opt-out.");
define("SUBACCOUNT_34", "Vielen Dank, dass Sie unsere Newsletter bewertet haben.");
define("SUBACCOUNT_35", "Informationen fehlen.");
define("SUBACCOUNT_36", "Email fehlt oder ist ungültig.");
define("SUBACCOUNT_37", "Senden Sie diese Newsletter Ihren Freunden");
define("SUBACCOUNT_38", "Newsletter");
define("SUBACCOUNT_39", "Mein Name");
define("SUBACCOUNT_40", "Meine Emailadresse");
define("SUBACCOUNT_41", "Ich möchte diese Newsletter weiterleiten an");
define("SUBACCOUNT_42", "Vorname");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Bestätigungscode");
define("SUBACCOUNT_45", "Senden");
define("SUBACCOUNT_46", "Datenschutz");
define("SUBACCOUNT_47", "Die Emailadressen Ihrer Freunde werden nicht gespeichert. Sie werden nur benutzt, um diese Newsletter weiterzuleiten.");
define("SUBACCOUNT_48", "Weitergeleitet durch ");
define("SUBACCOUNT_49", "Vielen Dank");
define("SUBACCOUNT_50", "Ihr Newsletter wurde weitergeleitet.");
define("SUBACCOUNT_51", "Folgende Person hat sich abgemeldet: ");
define("SUBACCOUNT_52", "Neues Opt-out");
define("SUBACCOUNT_53", "Sie haben eine neue Newsletter-Anmeldung: ");
define("SUBACCOUNT_54", "Neue Newsletter-Anmeldung");
define("SUBACCOUNT_55", "Abmelden");
// new lines in v.2.00
define("ARCHIVE_1", "Unsere Newsletters");
define("ARCHIVE_2", "Wählen Sie eine Newsletter");
define("ARCHIVE_3", "Newsletter-Archiv");
define("SUBACCOUNT_56", "Firma");
define("SUBACCOUNT_57", "Addresse");
define("SUBACCOUNT_58", "Stadt");
define("SUBACCOUNT_59", "PLZ");
define("SUBACCOUNT_60", "Region");
define("SUBACCOUNT_61", "Land");
define("SUBACCOUNT_62", "Tel. privat");
define("SUBACCOUNT_63", "Tel. Geschäft");
define("SUBACCOUNT_64", "Handy");
define("SUBACCOUNT_65", "Geburtstag");
define("SUBACCOUNT_66", "Selektieren");
// new lines in v.3.50
define("ARCHIVE_4", "No newsletters available");
define("SUBACCOUNT_67", "Missing data");
define("SUBACCOUNT_68", "You must enter your name and email and the verification code that you see.");
define("SUBACCOUNT_69", "Please enter valid emails.");
// new lines in v.3.60
define("SUBACCOUNT_70", "You clicked a correctly formatted opt-out link.<br>However, since this is a test email nothing happens.<br>In order to fully try your opt-out links send a campaign to your own test list.");
define("SUBACCOUNT_71", "You clicked a confirmation link.<br>However since this is a test email nothing will happen.<br>In order to fully test your confirmation link send a campaign to your own test list or subscribe using an opt-in form.");
}
else if ($subLang=='pt') { //PORTUGUESE
define("DEMOMODE_1", "Sorry, this feature is disabled in demo mode.");
define("SUBACCOUNT_1", "Suas assinaturas");
define("SUBACCOUNT_2", "Atualize sua conta");
define("SUBACCOUNT_3", "Digite o seu e-mail e senha para gerenciar suas assinaturas");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Enter");
define("SUBACCOUNT_6", "Caro");
define("SUBACCOUNT_7", "Aqui estão as listas disponíveis para você se inscrever:");
define("SUBACCOUNT_8", "Confira as listas que você deseja se inscrever, atualizar seus dados pessoais e clique em Atualizar.");
define("SUBACCOUNT_9", " Atualizar ");
define("SUBACCOUNT_10", "Lembrete de senha");
define("SUBACCOUNT_11", "Utilize este formulário para obter sua senha. Você receberá sua senha em seu email");
define("SUBACCOUNT_12", "Enviar senha");
define("SUBACCOUNT_13", "O email e senha que você digitou não existe em nosso banco de dados. Por favor, tente novamente.");
define("SUBACCOUNT_14", "Digite seu email!");
define("SUBACCOUNT_15", "Seu perfil foi atualizado");
define("SUBACCOUNT_16", "Sia senha é: ");
define("SUBACCOUNT_17", "Senha");
define("SUBACCOUNT_18", "Por favor informe um email válido");
define("SUBACCOUNT_19", "Por favor informe sua senha");
define("SUBACCOUNT_20", "Lembrete de senha do boletim ");
define("SUBACCOUNT_21", "Esta conta de  email não existe.");
define("SUBACCOUNT_22", "Enviamos sua senha.");
define("SUBACCOUNT_23", "Nome");
define("SUBACCOUNT_24", "Fechado");
define("SUBACCOUNT_25", "Sobrenome");
define("SUBACCOUNT_26", "Declaração de Privacidade");	
define("SUBACCOUNT_27", "Login information is missing.");
define("SUBACCOUNT_28", "Não há listas disponíveis.");
define("SUBACCOUNT_29", "Ajude-nos a melhorar");
define("SUBACCOUNT_30", "Por favor insira uma razão para cancelar");
define("SUBACCOUNT_31", "Informação cancelamento está faltando. Email em faltando ou inválido.");
define("SUBACCOUNT_32", "Cancelamento da Lista.");
define("SUBACCOUNT_33", "Cancelamento Global.");
define("SUBACCOUNT_34", "Thank you for rating our newsletter.");
define("SUBACCOUNT_35", "Está faltando informação.");
define("SUBACCOUNT_36", "Email is missing or not valid.");
define("SUBACCOUNT_37", "Encaminhar este boletim para seus amigos");
define("SUBACCOUNT_38", "Boletin");
define("SUBACCOUNT_39", "Meu nome");
define("SUBACCOUNT_40", "Meu email");
define("SUBACCOUNT_41", "Eu desejo enviar este boletim para");
define("SUBACCOUNT_42", "Nome");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Código de Verificação");
define("SUBACCOUNT_45", "Enviá-lo");
define("SUBACCOUNT_46", "Nota de privacidade");
define("SUBACCOUNT_47", "Endereços de email de seus amigos não são mantidos. Eles só serão usados para encaminhar este boletim.");
define("SUBACCOUNT_48", "transmitido pelo ");
define("SUBACCOUNT_49", "Obrigado");
define("SUBACCOUNT_50", "Seu boletim foi encaminhado.");
define("SUBACCOUNT_51", "Este assinante cancelar o registo: ");
define("SUBACCOUNT_52", "Nova opt-out");
define("SUBACCOUNT_53", "Você tem um novo assinante: ");
define("SUBACCOUNT_54", "Novo assinante");
define("SUBACCOUNT_55", "Anular");
// new lines in v.2.00
define("ARCHIVE_1", "Nossos boletins");
define("ARCHIVE_2", "Selecione um boletim");
define("ARCHIVE_3", "Arquivo de Boletins");
define("SUBACCOUNT_56", "Compania");
define("SUBACCOUNT_57", "Endereço");
define("SUBACCOUNT_58", "Cidade");
define("SUBACCOUNT_59", "Cep");
define("SUBACCOUNT_60", "Estado");
define("SUBACCOUNT_61", "País");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Celular ");
define("SUBACCOUNT_65", "Aniversário");
define("SUBACCOUNT_66", "Selecione");
// new lines in v.3.50
define("ARCHIVE_4", "Nenhum boletim disponível");
define("SUBACCOUNT_67", "Faltam dados");
define("SUBACCOUNT_68", "Você deve digitar seu nome e e-mail eo código de verificação que você vê.");
define("SUBACCOUNT_69", "Por favor insira e-mails válidos.");
// new lines in v.3.60
define("SUBACCOUNT_70", "You clicked a correctly formatted opt-out link.<br>However, since this is a test email nothing happens.<br>In order to fully try your opt-out links send a campaign to your own test list.");
define("SUBACCOUNT_71", "You clicked a confirmation link.<br>However since this is a test email nothing will happen.<br>In order to fully test your confirmation link send a campaign to your own test list or subscribe using an opt-in form.");
}
else {		//ENGLISH, if nothing is detected or not available.
define("DEMOMODE_1", "Sorry, this feature is disabled in demo mode.");
define("SUBACCOUNT_1", "Your Newsletter subscriptions");
define("SUBACCOUNT_2", "Update your subscriber account");
define("SUBACCOUNT_3", "Enter your email and password to see and manage your subscriptions");
define("SUBACCOUNT_4", "Email");
define("SUBACCOUNT_5", "Enter");
define("SUBACCOUNT_6", "Dear");
define("SUBACCOUNT_7", "Here are the available lists for you to subscribe:");
define("SUBACCOUNT_8", "Check the lists that you want to subscribe, make changes to your personal data and click on Update.");
define("SUBACCOUNT_9", " Update ");
define("SUBACCOUNT_10", "Password reminder");
define("SUBACCOUNT_11", "Use this form to obtain your password. You will receive your password in your email");
define("SUBACCOUNT_12", "Send password");
define("SUBACCOUNT_13", "The email and password you entered do not exist in our database. Please try again.");
define("SUBACCOUNT_14", "Please enter your email!");
define("SUBACCOUNT_15", "Your profile was updated");
define("SUBACCOUNT_16", "Your password is: ");
define("SUBACCOUNT_17", "Password");
define("SUBACCOUNT_18", "Please enter your valid email address");
define("SUBACCOUNT_19", "Please enter your password");
define("SUBACCOUNT_20", "Newsletter password reminder from ");
define("SUBACCOUNT_21", "This email account does not exist.");
define("SUBACCOUNT_22", "We have sent you your password.");
define("SUBACCOUNT_23", "Name");
define("SUBACCOUNT_24", "Close");
define("SUBACCOUNT_25", "Last name");
define("SUBACCOUNT_26", "Privacy statement");
define("SUBACCOUNT_27", "Login information is missing.");
define("SUBACCOUNT_28", "No available lists.");
define("SUBACCOUNT_29", "Help us improve");
define("SUBACCOUNT_30", "Please enter a reason for unsubscribing");
define("SUBACCOUNT_31", "Opt-out information is missing. Email missing or not valid.");
define("SUBACCOUNT_32", "List opt out.");
define("SUBACCOUNT_33", "Global opt out.");
define("SUBACCOUNT_34", "Thank you for rating our newsletter.");
define("SUBACCOUNT_35", "Information is missing.");
define("SUBACCOUNT_36", "Email is missing or not valid.");
define("SUBACCOUNT_37", "Forward this newsletter to your friends");
define("SUBACCOUNT_38", "Newsletter");
define("SUBACCOUNT_39", "My name");
define("SUBACCOUNT_40", "My email");
define("SUBACCOUNT_41", "I want to forward this newsletter to");
define("SUBACCOUNT_42", "Name");
define("SUBACCOUNT_43", "Email");
define("SUBACCOUNT_44", "Verification code");
define("SUBACCOUNT_45", "Send it");
define("SUBACCOUNT_46", "Privacy notice");
define("SUBACCOUNT_47", "Your friends' email addresses are not kept. They will only be used to forward this newsletter.");
define("SUBACCOUNT_48", "forwarded by ");
define("SUBACCOUNT_49", "Thank you");
define("SUBACCOUNT_50", "Your newsletter was forwarded.");
define("SUBACCOUNT_51", "This subscriber opted-out: ");
define("SUBACCOUNT_52", "New opt-out");
define("SUBACCOUNT_53", "You have a new subscriber: ");
define("SUBACCOUNT_54", "New subscriber");
define("SUBACCOUNT_55", "Un-subscribe");
// new lines in v.2.00
define("ARCHIVE_1", "Our newsletters");
define("ARCHIVE_2", "Select a newsletter");
define("ARCHIVE_3", "Newsletter archive");
define("SUBACCOUNT_56", "Company");
define("SUBACCOUNT_57", "Address");
define("SUBACCOUNT_58", "City");
define("SUBACCOUNT_59", "Zip");
define("SUBACCOUNT_60", "State");
define("SUBACCOUNT_61", "Country");
define("SUBACCOUNT_62", "Tel. 1");
define("SUBACCOUNT_63", "Tel. 2");
define("SUBACCOUNT_64", "Mobile ");
define("SUBACCOUNT_65", "Birthday");
define("SUBACCOUNT_66", "Select");
// new lines in v.3.50
define("ARCHIVE_4", "No newsletters available");
define("SUBACCOUNT_67", "Missing data");
define("SUBACCOUNT_68", "You must enter your name and email and the verification code that you see.");
define("SUBACCOUNT_69", "Please enter valid emails.");
// new lines in v.3.60
define("SUBACCOUNT_70", "You clicked a correctly formatted opt-out link.<br>However, since this is a test email nothing happens.<br>In order to fully try your opt-out links send a campaign to your own test list.");
define("SUBACCOUNT_71", "You clicked a confirmation link.<br>However since this is a test email nothing will happen.<br>In order to fully test your confirmation link send a campaign to your own test list or subscribe using an opt-in form.");
}
?>